import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "@minecraft/server-ui";
import * as Exchanges from "../core/exchanges.js";
import * as Economy from "../core/economy.js";
import * as Inventory from "../services/inventory.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
export function openExchange(player){const xs=Exchanges.list(),pick=new ObservableNumber(0,{clientWritable:true}),info=new ObservableString(""),f=new CustomForm(player,"Moneyz Exchange");const refresh=()=>{const x=xs[pick.getData()];info.setData(x?`${x.itemAmount} ${x.name} ↔ ${x.moneyz} Moneyz\nBalance: ${Economy.getBalance(player)}\nYou have: ${Inventory.count(player,x.itemId)}`:"No exchanges configured.")};pick.subscribe(refresh);refresh();if(xs.length)f.dropdown("Exchange",pick,xs.map((x,i)=>({label:x.name,value:i}))).label(info).button("Resources → Moneyz",()=>nav(f,()=>trade(player,xs[pick.getData()],"sell"))).button("Moneyz → Resources",()=>nav(f,()=>trade(player,xs[pick.getData()],"buy")));else f.label("No exchange definitions are enabled.");f.closeButton().show();}
function trade(player,x,direction){if(!x)return openExchange(player);const max=direction==="sell"?Math.max(1,Math.min(64,Math.floor(Inventory.count(player,x.itemId)/x.itemAmount)||1)):Math.max(1,Math.min(64,Math.floor(Economy.getBalance(player)/x.moneyz)||1)),qty=new ObservableNumber(1,{clientWritable:true}),f=new CustomForm(player,x.name);f.label(`${x.itemAmount} ${x.name} = ${x.moneyz} Moneyz`).slider("Bundles",qty,1,max,{step:1}).button("Confirm",async()=>{const r=await Exchanges.execute(player,x.id,direction,qty.getData());player.sendMessage(r.ok?`§aExchange complete: ${r.items} items / ${r.money} Moneyz.`:`§cExchange failed: ${r.reason}`);nav(f,()=>openExchange(player));}).button("Back",()=>nav(f,()=>openExchange(player))).closeButton().show();}
export function exchangeAdmin(player){const xs=Exchanges.all(),pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Exchange Manager");if(xs.length)f.dropdown("Exchange",pick,xs.map((x,i)=>({label:`${x.name} • ${x.itemAmount} ↔ ${x.moneyz}`,value:i}))).button("Edit Selected",()=>nav(f,()=>edit(player,xs[pick.getData()])));f.button("Create Exchange",()=>nav(f,()=>edit(player,null))).button("Back",()=>import("./admin_menu.js").then(m=>m.moneyzAdmin(player))).closeButton().show();}
function edit(player,x){const id=new ObservableString(x?.id??"",{clientWritable:true}),name=new ObservableString(x?.name??"",{clientWritable:true}),item=new ObservableString(x?.itemId??"minecraft:emerald",{clientWritable:true}),amount=new ObservableString(String(x?.itemAmount??1),{clientWritable:true}),money=new ObservableString(String(x?.moneyz??1),{clientWritable:true}),f=new CustomForm(player,x?"Edit Exchange":"Create Exchange");f.textField("ID",id).textField("Display name",name).textField("Item ID",item).textField("Item quantity",amount).textField("Moneyz",money).button("Save",()=>{try{Exchanges.upsert({id:id.getData(),name:name.getData(),itemId:item.getData(),itemAmount:Number(amount.getData()),moneyz:Number(money.getData())});player.sendMessage("§aExchange saved.");nav(f,()=>exchangeAdmin(player));}catch(e){player.sendMessage(`§c${e}`)}});if(x)f.button("Delete",()=>{Exchanges.remove(x.id);nav(f,()=>exchangeAdmin(player));});f.button("Back",()=>nav(f,()=>exchangeAdmin(player))).closeButton().show();}
