import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "@minecraft/server-ui";
import * as T from "../core/item_templates.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
const pretty=s=>String(s??"").replace(/^minecraft:/,"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const copy=v=>JSON.parse(JSON.stringify(v));

export function chooseItemTemplate(player,{title="Item Template",initial=null,onSave,onBack}={}){
 const spec=initial?copy(initial):null,f=new CustomForm(player,title);
 f.label(spec?`§fCurrent: §a${T.describe(spec)}`:"§7Choose how to define the exact item that will be delivered.");
 f.button("Select Runtime Item / Block",()=>nav(f,()=>search(player,{title,initial:spec,onSave,onBack})));
 f.button("Create Potion / Tipped Arrow",()=>nav(f,()=>potion(player,{title,initial:spec,onSave,onBack})));
 f.button("Capture Held Item",()=>{const c=player.getComponent("minecraft:inventory")?.container,held=c?.getItem(player.selectedSlotIndex??0);if(!held){player.sendMessage("§cHold the exact item first.");return;}configure(player,T.capture(held,{amount:1}),{title,onSave,onBack});});
 if(spec)f.button("Configure Current Item",()=>nav(f,()=>configure(player,spec,{title,onSave,onBack})));
 f.button("Back",()=>nav(f,()=>onBack?.())).closeButton().show();
}
function search(player,ctx){const q=new ObservableString("",{clientWritable:true}),f=new CustomForm(player,"Runtime Item Registry");f.textField("Search Item / Block ID",q,{description:"Uses the running world's ItemTypes registry, including add-on items."}).button("Search",()=>nav(f,()=>results(player,q.getData(),ctx))).button("Browse First 150",()=>nav(f,()=>results(player,"",ctx))).button("Back",()=>nav(f,()=>chooseItemTemplate(player,ctx))).closeButton().show();}
function results(player,q,ctx){const ids=T.itemCatalog(q,150);if(!ids.length){player.sendMessage("§cNo runtime items matched.");return search(player,ctx);}const p=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Runtime Items");f.dropdown("Item",p,ids.map((id,i)=>({label:`${pretty(id)} — ${id}`,value:i}))).button("Configure",()=>nav(f,()=>configure(player,{version:1,typeId:ids[p.getData()],amount:1},{...ctx}))).button("Back",()=>nav(f,()=>search(player,ctx))).closeButton().show();}
function configure(player,spec,ctx){spec=copy(spec);const f=new CustomForm(player,"Configure Item Variant"),amount=new ObservableString(String(spec.amount??1),{clientWritable:true}),name=new ObservableString(spec.nameTag??"",{clientWritable:true}),lore=new ObservableString((spec.lore??[]).join("\\n"),{clientWritable:true});f.label(`§a${T.describe(spec)}\n§7${spec.typeId}`).textField("Quantity",amount).textField("Custom Name (optional)",name).textField("Lore (use \\n between lines)",lore);
 if(T.supportsEnchantments(spec))f.button(`Enchantments (${spec.enchantments?.length??0})`,()=>{spec.amount=Math.max(1,parseInt(amount.getData())||1);spec.nameTag=name.getData()||undefined;spec.lore=lore.getData()?lore.getData().split("\\n"):undefined;nav(f,()=>enchantments(player,spec,ctx));});
 if(spec.potion)f.button("Change Potion / Arrow Variant",()=>nav(f,()=>potion(player,{...ctx,initial:spec})));
 f.button("Save Exact Item",()=>{spec.amount=Math.max(1,parseInt(amount.getData())||1);const n=name.getData().trim();if(n)spec.nameTag=n;else delete spec.nameTag;const l=lore.getData();if(l)spec.lore=l.split("\\n");else delete spec.lore;const v=T.validate(spec);if(!v.ok){player.sendMessage(`§cInvalid item template: ${v.message??v.reason}`);return;}nav(f,()=>ctx.onSave?.(spec));}).button("Back",()=>nav(f,()=>chooseItemTemplate(player,{...ctx,initial:spec}))).closeButton().show();}
function enchantments(player,spec,ctx){const current=spec.enchantments??[],f=new CustomForm(player,"Enchantments");f.label(current.length?current.map(x=>`§b${pretty(x.id)} ${x.level}`).join("\n"):"§7No enchantments configured.").button("Add Enchantment",()=>nav(f,()=>addEnchant(player,spec,ctx)));if(current.length)f.button("Remove Enchantment",()=>nav(f,()=>removeEnchant(player,spec,ctx))).button("Clear All",()=>{delete spec.enchantments;nav(f,()=>enchantments(player,spec,ctx));});f.button("Back",()=>nav(f,()=>configure(player,spec,ctx))).closeButton().show();}
function addEnchant(player,spec,ctx){const rows=T.applicableEnchantments(spec).filter(x=>!(spec.enchantments??[]).some(e=>e.id===x.id));if(!rows.length){player.sendMessage("§eNo additional compatible runtime enchantments are available for this item.");return enchantments(player,spec,ctx);}const p=new ObservableNumber(0,{clientWritable:true}),lvl=new ObservableString("1",{clientWritable:true}),f=new CustomForm(player,"Add Enchantment");f.dropdown("Compatible Enchantment",p,rows.map((x,i)=>({label:`${pretty(x.id)} (max ${x.maxLevel})`,value:i}))).textField("Level",lvl,{description:"Must be within the runtime enchantment's supported level range."}).button("Add",()=>{const row=rows[p.getData()],level=Math.max(1,Math.min(row.maxLevel,parseInt(lvl.getData())||1)),next=copy(spec);next.enchantments=[...(next.enchantments??[]),{id:row.id,level}];const v=T.validate(next);if(!v.ok){player.sendMessage(`§cThat combination is not compatible: ${v.message??v.reason}`);return;}nav(f,()=>enchantments(player,next,ctx));}).button("Back",()=>nav(f,()=>enchantments(player,spec,ctx))).closeButton().show();}
function removeEnchant(player,spec,ctx){const rows=spec.enchantments??[],p=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Remove Enchantment");f.dropdown("Enchantment",p,rows.map((x,i)=>({label:`${pretty(x.id)} ${x.level}`,value:i}))).button("Remove",()=>{spec.enchantments=rows.filter((_,i)=>i!==p.getData());if(!spec.enchantments.length)delete spec.enchantments;nav(f,()=>enchantments(player,spec,ctx));}).button("Back",()=>nav(f,()=>enchantments(player,spec,ctx))).closeButton().show();}
function potion(player,ctx){const valid=T.potionVariants();if(!valid.length){player.sendMessage("§cThe runtime reported no constructible potion variants.");return chooseItemTemplate(player,ctx);}const initialIndex=Math.max(0,valid.findIndex(x=>x.effectId===ctx.initial?.potion?.effectId&&x.deliveryId===ctx.initial?.potion?.deliveryId)),pick=new ObservableNumber(initialIndex,{clientWritable:true}),f=new CustomForm(player,"Potion / Tipped Arrow");f.label("§7Only effect + delivery combinations successfully constructed by the running Minecraft Potions.resolve() registry are listed. This includes supported potion, splash/lingering, and arrow delivery variants exposed by this Minecraft version.").dropdown("Runtime Potion Variant",pick,valid.map((x,i)=>({label:`${pretty(x.effectId)} • ${pretty(x.deliveryId)} • ${x.typeId}`,value:i}))).button("Use Variant",()=>{const v=valid[pick.getData()];const spec={version:1,typeId:v.typeId,amount:ctx.initial?.amount??1,potion:{effectId:v.effectId,deliveryId:v.deliveryId}};nav(f,()=>configure(player,spec,ctx));}).button("Back",()=>nav(f,()=>chooseItemTemplate(player,ctx))).closeButton().show();}
