import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "../ui/ddui.js";
import * as T from "../core/item_templates.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
const pretty=s=>String(s??"").replace(/^minecraft:/,"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const copy=v=>JSON.parse(JSON.stringify(v));

export function chooseItemTemplate(player,{title="Item Template",initial=null,onSave,onBack}={}){
 const spec=initial?copy(initial):null,f=new CustomForm(player,title);
 f.label(spec?`§fCurrent: §a${T.describe(spec)}`:"§7Choose how to define the exact item that will be delivered.");
 f.button("Select Runtime Item / Block",()=>nav(f,()=>search(player,{title,initial:spec,onSave,onBack})));
 f.button("Create Potion",()=>nav(f,()=>potion(player,{title,initial:spec,onSave,onBack})));
 f.button("Create Tipped Arrow",()=>nav(f,()=>tippedArrow(player,{title,initial:spec,onSave,onBack})));
 f.button("Capture Held Item",()=>{const c=player.getComponent("minecraft:inventory")?.container,held=c?.getItem(player.selectedSlotIndex??0);if(!held){player.sendMessage("§cHold the exact item first.");return;}configure(player,T.capture(held,{amount:1}),{title,onSave,onBack});});
 if(spec)f.button("Configure Current Item",()=>nav(f,()=>configure(player,spec,{title,onSave,onBack})));
 f.button("Back",()=>nav(f,()=>onBack?.())).closeButton().show();
}
function search(player,ctx){const q=new ObservableString("",{clientWritable:true}),f=new CustomForm(player,"Runtime Item Registry");f.textField("Search Item / Block ID",q,{description:"Uses the running world's ItemTypes registry, including add-on items."}).button("Search",()=>nav(f,()=>results(player,q.getData(),ctx))).button("Browse First 150",()=>nav(f,()=>results(player,"",ctx))).button("Back",()=>nav(f,()=>chooseItemTemplate(player,ctx))).closeButton().show();}
function results(player,q,ctx){const ids=T.itemCatalog(q,150);if(!ids.length){player.sendMessage("§cNo runtime items matched.");return search(player,ctx);}const p=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Runtime Items");f.dropdown("Item",p,ids.map((id,i)=>({label:`${pretty(id)} — ${id}`,value:i}))).button("Configure",()=>nav(f,()=>configure(player,{version:1,typeId:ids[p.getData()],amount:1},{...ctx}))).button("Back",()=>nav(f,()=>search(player,ctx))).closeButton().show();}
function configure(player,spec,ctx){spec=copy(spec);const f=new CustomForm(player,"Configure Item Variant"),amount=new ObservableString(String(spec.amount??1),{clientWritable:true}),name=new ObservableString(spec.nameTag??"",{clientWritable:true}),lore=new ObservableString((spec.lore??[]).join("\\n"),{clientWritable:true});f.label(`§a${T.describe(spec)}\n§7${spec.typeId}`).textField("Quantity",amount).textField("Custom Name (optional)",name).textField("Lore (use \\n between lines)",lore);
 if(T.supportsEnchantments(spec))f.button(`Enchantments (${spec.enchantments?.length??0})`,()=>{spec.amount=Math.max(1,parseInt(amount.getData())||1);spec.nameTag=name.getData()||undefined;spec.lore=lore.getData()?lore.getData().split("\\n"):undefined;nav(f,()=>enchantments(player,spec,ctx));});
 if(spec.potion)f.button("Change Potion Variant",()=>nav(f,()=>potion(player,{...ctx,initial:spec})));
 if(spec.tippedArrow)f.button("Change Tipped Arrow Variant",()=>nav(f,()=>tippedArrow(player,{...ctx,initial:spec})));
 f.button("Save Exact Item",()=>{spec.amount=Math.max(1,parseInt(amount.getData())||1);const n=name.getData().trim();if(n)spec.nameTag=n;else delete spec.nameTag;const l=lore.getData();if(l)spec.lore=l.split("\\n");else delete spec.lore;const v=T.validate(spec);if(!v.ok){player.sendMessage(`§cInvalid item template: ${v.message??v.reason}`);return;}nav(f,()=>ctx.onSave?.(spec));}).button("Back",()=>nav(f,()=>chooseItemTemplate(player,{...ctx,initial:spec}))).closeButton().show();}
function enchantments(player,spec,ctx){const current=spec.enchantments??[],f=new CustomForm(player,"Enchantments");f.label(current.length?current.map(x=>`§b${pretty(x.id)} ${x.level}`).join("\n"):"§7No enchantments configured.").button("Add Enchantment",()=>nav(f,()=>addEnchant(player,spec,ctx)));if(current.length)f.button("Remove Enchantment",()=>nav(f,()=>removeEnchant(player,spec,ctx))).button("Clear All",()=>{delete spec.enchantments;nav(f,()=>enchantments(player,spec,ctx));});f.button("Back",()=>nav(f,()=>configure(player,spec,ctx))).closeButton().show();}
function addEnchant(player,spec,ctx){const rows=T.applicableEnchantments(spec).filter(x=>!(spec.enchantments??[]).some(e=>e.id===x.id));if(!rows.length){player.sendMessage("§eNo additional compatible runtime enchantments are available for this item.");return enchantments(player,spec,ctx);}const p=new ObservableNumber(0,{clientWritable:true}),lvl=new ObservableString("1",{clientWritable:true}),f=new CustomForm(player,"Add Enchantment");f.dropdown("Compatible Enchantment",p,rows.map((x,i)=>({label:`${pretty(x.id)} (max ${x.maxLevel})`,value:i}))).textField("Level",lvl,{description:"Must be within the runtime enchantment's supported level range."}).button("Add",()=>{const row=rows[p.getData()],level=Math.max(1,Math.min(row.maxLevel,parseInt(lvl.getData())||1)),next=copy(spec);next.enchantments=[...(next.enchantments??[]),{id:row.id,level}];const v=T.validate(next);if(!v.ok){player.sendMessage(`§cThat combination is not compatible: ${v.message??v.reason}`);return;}nav(f,()=>enchantments(player,next,ctx));}).button("Back",()=>nav(f,()=>enchantments(player,spec,ctx))).closeButton().show();}
function removeEnchant(player,spec,ctx){const rows=spec.enchantments??[],p=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Remove Enchantment");f.dropdown("Enchantment",p,rows.map((x,i)=>({label:`${pretty(x.id)} ${x.level}`,value:i}))).button("Remove",()=>{spec.enchantments=rows.filter((_,i)=>i!==p.getData());if(!spec.enchantments.length)delete spec.enchantments;nav(f,()=>enchantments(player,spec,ctx));}).button("Back",()=>nav(f,()=>enchantments(player,spec,ctx))).closeButton().show();}
function potion(player,ctx){const all=T.potionVariants();if(!all.length){player.sendMessage("§cThe runtime reported no constructible potion variants.");return chooseItemTemplate(player,ctx);}const deliveries=[...new Map(all.map(v=>[v.deliveryId,v])).values()].map(v=>v.deliveryId),initialDelivery=ctx.initial?.potion?.deliveryId,dIndex=Math.max(0,deliveries.indexOf(initialDelivery)),deliveryPick=new ObservableNumber(dIndex,{clientWritable:true}),f=new CustomForm(player,"Potion");f.label("§7Choose a runtime potion delivery form. This list intentionally contains potions only; tipped arrows have their own Bedrock arrow selector.").dropdown("Delivery Type",deliveryPick,deliveries.map((id,i)=>({label:pretty(id),value:i}))).button("Choose Effect",()=>{const deliveryId=deliveries[deliveryPick.getData()]??deliveries[0];nav(f,()=>potionEffects(player,deliveryId,ctx));}).button("Back",()=>nav(f,()=>chooseItemTemplate(player,ctx))).closeButton().show();}
function potionEffects(player,deliveryId,ctx){const families=T.potionFamilies(deliveryId);if(!families.length)return potion(player,ctx);const initialInfo=ctx.initial?.potion?.effectId?T.potionVariantInfo(ctx.initial.potion.effectId):null,initial=Math.max(0,families.findIndex(x=>x.family===initialInfo?.family)),pick=new ObservableNumber(initial,{clientWritable:true}),f=new CustomForm(player,`${pretty(deliveryId)} Effect`);f.label(`§7Delivery: §f${pretty(deliveryId)}\n§7Choose the potion effect first. Only effect families with runtime-resolvable variants are shown.`).dropdown("Effect",pick,families.map((x,i)=>({label:pretty(x.family),value:i}))).button("Choose Variant / Level",()=>{const family=families[pick.getData()]??families[0];nav(f,()=>potionLevels(player,deliveryId,family,ctx));}).button("Back",()=>nav(f,()=>potion(player,ctx))).closeButton().show();}
function potionLevels(player,deliveryId,family,ctx){const rows=family?.variants??[];if(!rows.length)return potionEffects(player,deliveryId,ctx);const initial=Math.max(0,rows.findIndex(x=>x.effectId===ctx.initial?.potion?.effectId)),pick=new ObservableNumber(initial,{clientWritable:true}),f=new CustomForm(player,`${pretty(family.family)} Variant`);f.label(`§7Effect: §f${pretty(family.family)}\n§7Delivery: §f${pretty(deliveryId)}\n§7Choose the exact registered variant. Standard, extended-duration, and enhanced/II options appear only when Minecraft exposes them for this delivery type.`).dropdown("Variant / Level",pick,rows.map((x,i)=>({label:`${x.variant} — ${pretty(x.effectId)}`,value:i}))).button("Use Variant",()=>{const v=rows[pick.getData()]??rows[0],spec={version:1,typeId:v.typeId,amount:ctx.initial?.amount??1,potion:{effectId:v.effectId,deliveryId:v.deliveryId}};nav(f,()=>configure(player,spec,ctx));}).button("Back",()=>nav(f,()=>potionEffects(player,deliveryId,ctx))).closeButton().show();}
function tippedArrow(player,ctx){const rows=T.tippedArrowVariants();if(!rows.length){player.sendMessage("§cNo supported tipped-arrow variants are configured for this Bedrock build.");return chooseItemTemplate(player,ctx);}const groups=new Map();for(const row of rows){const family=String(row.name).replace(/ \([^)]*\)$/,'').replace(/ II$/,'');if(!groups.has(family))groups.set(family,[]);groups.get(family).push(row);}const families=[...groups.entries()].map(([name,variants])=>({name,variants})),current=rows.find(x=>x.data===ctx.initial?.tippedArrow?.data),currentFamily=current?String(current.name).replace(/ \([^)]*\)$/,'').replace(/ II$/,''):null,initial=Math.max(0,families.findIndex(x=>x.name===currentFamily)),pick=new ObservableNumber(initial,{clientWritable:true}),f=new CustomForm(player,"Tipped Arrow");f.label("§7Choose the arrow effect first. Tipped arrows use their own Bedrock item-data variants and are kept separate from potion delivery types.").dropdown("Arrow Effect",pick,families.map((x,i)=>({label:x.name,value:i}))).button("Choose Variant / Level",()=>{const family=families[pick.getData()]??families[0];nav(f,()=>tippedArrowLevel(player,family,ctx));}).button("Normal Arrow",()=>nav(f,()=>configure(player,{version:1,typeId:"minecraft:arrow",amount:ctx.initial?.amount??1},ctx))).button("Back",()=>nav(f,()=>chooseItemTemplate(player,ctx))).closeButton().show();}
function tippedArrowLevel(player,family,ctx){const rows=family?.variants??[];if(!rows.length)return tippedArrow(player,ctx);const initial=Math.max(0,rows.findIndex(x=>x.data===ctx.initial?.tippedArrow?.data)),pick=new ObservableNumber(initial,{clientWritable:true}),f=new CustomForm(player,`${family.name} Arrow Variant`);f.label(`§7Choose the exact ${family.name} arrow variant/level. Duration and II/enhanced variants are separate Bedrock item-data values.`).dropdown("Variant / Level",pick,rows.map((x,i)=>({label:x.name,value:i}))).button("Use Tipped Arrow",()=>{const v=rows[pick.getData()]??rows[0],spec={version:1,typeId:"minecraft:arrow",amount:ctx.initial?.amount??1,tippedArrow:{data:v.data,name:v.name}};nav(f,()=>configure(player,spec,ctx));}).button("Back",()=>nav(f,()=>tippedArrow(player,ctx))).closeButton().show();}

