import { system } from "@minecraft/server";
import { CustomForm, ObservableBoolean, ObservableNumber, ObservableString } from "../ui/ddui.js";
import * as Jobs from "../core/jobs.js";
import { main } from "./moneyz_menu.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
export function openJobs(player){const st=Jobs.state(player),f=new CustomForm(player,"Jobs");f.header("Employment Services").label(st.job?`Current job: ${st.job.name}\nPay grade: ${st.job.pay} Moneyz per payroll.`:`You are currently unemployed.\n${st.hasApplication?"Application permit ready.":"Get an application permit before choosing a job."}`);if(!st.job&&!st.hasApplication)f.button("Get Application Permit",()=>{Jobs.grantApplication(player,{source:"jobs_ui"});player.sendMessage("§aApplication permit granted. Choose a job when ready.");nav(f,()=>openJobs(player));});if(st.job)f.button("Quit Job",()=>{Jobs.leave(player,{source:"jobs_ui"});player.sendMessage("§eYou left your job.");nav(f,()=>openJobs(player));});f.button("Browse Jobs",()=>nav(f,()=>browseJobs(player)));if(Jobs.canRunPayroll(player))f.button("Run Worker Payroll",()=>nav(f,()=>openPayroll(player)));f.button("Back",()=>nav(f,()=>main(player))).closeButton().show();}
function browseJobs(player){const jobs=Jobs.list();if(!jobs.length){const empty=new CustomForm(player,"Available Jobs");empty.label("No jobs are currently available.").button("Back to Jobs",()=>nav(empty,()=>openJobs(player))).closeButton().show();return;}const pick=new ObservableNumber(0,{clientWritable:true}),info=new ObservableString(""),f=new CustomForm(player,"Available Jobs");const refresh=()=>{const j=jobs[pick.getData()];info.setData(j?`${j.description||""}\nPay grade: ${j.pay} Moneyz per payroll.${j.requiresApplication!==false?"\nApplication permit required.":""}`:"")};pick.subscribe(refresh);refresh();f.dropdown("Job",pick,jobs.map((j,i)=>({label:j.name,value:i}))).label(info).button("Apply",()=>{const j=jobs[pick.getData()],r=j&&Jobs.join(player,j.id,{source:"jobs_ui"});player.sendMessage(r?.ok?`§aYou are now employed as ${j.name}.`:r?.reason==="application_required"?"§cGet an application permit first.":`§cCould not join: ${r?.reason??"unknown"}.`);nav(f,()=>openJobs(player));}).button("Back",()=>nav(f,()=>openJobs(player))).closeButton().show();}
export function openPayroll(player){const f=new CustomForm(player,"Worker Payroll");if(!Jobs.canRunPayroll(player)){f.header("Worker Payroll").label("Only a Banker can run payroll.").button("Back",()=>nav(f,()=>openJobs(player))).closeButton().show();return;}const workers=[...Jobs.list()].map(j=>`${j.name}: ${j.pay} Moneyz`).join("\n");f.header("Worker Payroll").label(`Pay all online employed players using their configured pay grade.\n\n${workers}`).button("Run Payroll",()=>{const r=Jobs.runPayroll(player,{source:"payroll_ui"});player.sendMessage(r.ok?`§aPayroll complete: ${r.count} worker(s), ${r.total} Moneyz paid.`:`§cPayroll failed: ${r.reason}.`);nav(f,()=>openJobs(player));}).button("Back",()=>nav(f,()=>openJobs(player))).closeButton().show();}
export function jobAdmin(player){const jobs=Jobs.listAll(),pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Job Manager");f.header("Dynamic Jobs").label("Create jobs, set payroll amounts, and manage application requirements.");if(jobs.length)f.dropdown("Existing job",pick,jobs.map((j,i)=>({label:`${j.name} • ${j.pay} Moneyz`,value:i}))).button("Edit Selected",()=>nav(f,()=>editJob(player,jobs[pick.getData()])));f.button("Create Job",()=>nav(f,()=>editJob(player,null))).button("Back",()=>nav(f,()=>import("./admin_menu.js").then(m=>m.moneyzAdmin(player)))).closeButton().show();}
function editJob(player,job){const id=new ObservableString(job?.id??"",{clientWritable:true}),name=new ObservableString(job?.name??"",{clientWritable:true}),desc=new ObservableString(job?.description??"",{clientWritable:true}),pay=new ObservableString(String(job?.pay??1000),{clientWritable:true}),tags=new ObservableString((job?.legacyTags??[]).join(", "),{clientWritable:true}),application=new ObservableBoolean(job?.requiresApplication!==false,{clientWritable:true}),f=new CustomForm(player,job?"Edit Job":"Create Job");f.textField("Job ID",id,{description:"Stable id, e.g. msv_police"}).textField("Display name",name).textField("Description",desc).textField("Pay per payroll",pay).toggle("Require application permit",application).textField("Legacy tags",tags,{description:"Comma-separated tags to migrate/maintain"}).button("Save",()=>{try{Jobs.upsert({id:id.getData(),name:name.getData(),description:desc.getData(),pay:Number(pay.getData()),requiresApplication:application.getData(),legacyTags:tags.getData().split(",").map(x=>x.trim()).filter(Boolean)});player.sendMessage("§aJob saved.");nav(f,()=>jobAdmin(player));}catch(e){player.sendMessage(`§c${e}`)}});if(job)f.button("Delete",()=>{Jobs.remove(job.id);nav(f,()=>jobAdmin(player));});f.button("Back",()=>nav(f,()=>jobAdmin(player))).closeButton().show();}
