import { ActionFormData } from "../ui/forms.js";
import { getCurrentUTCDate } from "../utilities.js";
import * as Economy from "../core/economy.js";
import * as Lucky from "../core/lucky.js";
import { luckyMenu } from "./lucky_menu.js";
import { log, LOG_LEVELS } from "../logger.js";
import * as Config from "../core/config.js";

export async function luckyPurchase(player,isNpcInteraction){if(!player)return;const currentDate=getCurrentUTCDate(),once=Config.bool("oneLuckyPurchase",true),last=player.getDynamicProperty("lastLuckyPurchase");if(once&&last===currentDate){new ActionFormData().title("§l§cLucky Purchase Restricted").body("§cYou have already made your Lucky Purchase today.\n§7Try again tomorrow!").button("§c§lBack").show(player);return;}const cfg=Lucky.getConfig(),eligible=Lucky.eligibleProducts();new ActionFormData().title("§l§1Lucky Purchase").body(`§l§o§fMake a Lucky Purchase for ${cfg.price} Moneyz!§r\n§7Your reward is randomly selected from ${eligible.length} currently eligible in-stock Shop products. Its Shop value may be lower or higher than the price you pay.`).button("§a§lMake Purchase").button("§c§lBack").show(player).then(async r=>{if(!r||r.canceled)return;if(r.selection===0){const result=await Lucky.purchase(player);if(!result.ok){try{player.playSound("note.bass");}catch{}const msg=result.reason==="insufficient_funds"?`§cYou need ${cfg.price} Moneyz for this purchase\n§6You have ${Economy.getBalance(player)} Moneyz`:result.reason==="no_eligible_products"?"§cThere are currently no eligible in-stock Shop products for Lucky Purchase.":`§cLucky Purchase failed: ${result.reason}`;player.sendMessage(msg);return;}try{player.playSound("random.levelup");}catch{}player.sendMessage(`§aYou made a Lucky Purchase!\n§7Received: §f${result.product.name} ×${result.product.amount}\n§7Shop Value: §6${result.value} Moneyz §8(Paid ${result.price})`);if(once)player.setDynamicProperty("lastLuckyPurchase",currentDate);}else if(r.selection===1&&!isNpcInteraction)luckyMenu(player);}).catch(err=>log(`Error in luckyPurchase form: ${err}`,LOG_LEVELS.ERROR));}
log("lucky_purchase.js loaded",LOG_LEVELS.DEBUG);
