import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "@minecraft/server-ui";
import * as Products from "../core/products.js";
import { LEGACY_PRODUCT_TEMPLATES } from "../data/legacy_product_templates.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
export function openProducts(player,{type}={}){const ps=Products.list({type}),pick=new ObservableNumber(0,{clientWritable:true}),info=new ObservableString(""),f=new CustomForm(player,type==="pet"?"Pet Shop":"Products & Services");const refresh=()=>{const p=ps[pick.getData()];info.setData(p?`${p.description??""}\nType: ${p.type}\nPrice: ${p.price} Moneyz`:"No products configured.")};pick.subscribe(refresh);refresh();if(ps.length)f.dropdown("Product",pick,ps.map((p,i)=>({label:p.name,value:i}))).label(info).button("Purchase",async()=>{const p=ps[pick.getData()],r=p&&await Products.purchase(player,p.id,{source:"product_ui"});player.sendMessage(r?.ok?`§aPurchased ${p.name}.`:`§cPurchase failed: ${r?.reason}`);nav(f,()=>openProducts(player,{type}));});else f.label("No products are configured.");f.closeButton().show();}
export function productAdmin(player){const ps=Products.all(),pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Product / Bundle Manager");if(ps.length)f.dropdown("Product",pick,ps.map((p,i)=>({label:`${p.name} • ${p.type} • ${p.price}`,value:i}))).button("Edit Selected",()=>nav(f,()=>edit(player,ps[pick.getData()])));f.button("Create Product",()=>nav(f,()=>edit(player,null))).button("Import Legacy Premium Products",()=>{const r=Products.importDefinitions(LEGACY_PRODUCT_TEMPLATES);player.sendMessage(`§aLegacy templates: ${r.added} added, ${r.skipped} already present.`);nav(f,()=>productAdmin(player));}).button("Back",()=>import("./admin_menu.js").then(m=>m.moneyzAdmin(player))).closeButton().show();}
function edit(player,p){const types=["item","bundle","pet","entitlement","reservation","xp","legacy_structure"],id=new ObservableString(p?.id??"",{clientWritable:true}),name=new ObservableString(p?.name??"",{clientWritable:true}),desc=new ObservableString(p?.description??"",{clientWritable:true}),type=new ObservableNumber(Math.max(0,types.indexOf(p?.type??"item")),{clientWritable:true}),price=new ObservableString(String(p?.price??0),{clientWritable:true}),payload=new ObservableString(payloadText(p),{clientWritable:true}),f=new CustomForm(player,p?"Edit Product":"Create Product");f.textField("ID",id).textField("Name",name).textField("Description",desc).dropdown("Type",type,types.map((x,i)=>({label:x,value:i}))).textField("Price",price).textField("Payload",payload,{description:"item: minecraft:id[,amount] | pet: entity id | entitlement: id | reservation: property id | bundle: item*qty;item*qty"}).button("Save",()=>{try{const t=types[type.getData()],def={id:id.getData(),name:name.getData(),description:desc.getData(),type:t,price:Number(price.getData())};applyPayload(def,payload.getData());Products.upsert(def);player.sendMessage("§aProduct saved.");nav(f,()=>productAdmin(player));}catch(e){player.sendMessage(`§c${e}`)}});if(p)f.button("Delete",()=>{Products.remove(p.id);nav(f,()=>productAdmin(player));});f.button("Back",()=>nav(f,()=>productAdmin(player))).closeButton().show();}
function payloadText(p){if(!p)return "";if(p.type==="item")return `${p.itemId??""},${p.amount??1}`;if(p.type==="pet"||p.type==="entity")return p.entityId??"";if(p.type==="entitlement")return p.entitlementId??"";if(p.type==="reservation")return p.propertyId??"";if(p.type==="bundle")return (p.contents??[]).map(x=>`${x.itemId??x.id}*${x.amount??1}`).join(";");if(p.type==="xp")return String(p.xp??5);if(p.type==="legacy_structure")return `${p.structureName??""}|${p.structurePosition??"~ ~ ~"}`;return "";}
function applyPayload(d,v){v=String(v??"").trim();if(d.type==="item"){const [id,n]=v.split(",");d.itemId=id?.trim();d.amount=Math.max(1,Number(n)||1);if(!d.itemId)throw new Error("Item ID required");}else if(d.type==="pet"){d.entityId=v;if(!v)throw new Error("Entity ID required");}else if(d.type==="entitlement"){d.entitlementId=v;if(!v)throw new Error("Entitlement ID required");}else if(d.type==="reservation"){d.propertyId=v;if(!v)throw new Error("Hotel property ID required");}else if(d.type==="xp"){d.xp=Math.max(1,Number(v)||1);}else if(d.type==="legacy_structure"){const [structureName,structurePosition]=v.split("|");d.structureName=structureName?.trim();d.structurePosition=structurePosition?.trim()||"~ ~ ~";if(!d.structureName)throw new Error("Structure name required");}else if(d.type==="bundle"){d.contents=v.split(";").map(s=>{const [itemId,n]=s.trim().split("*");return {type:"item",itemId,amount:Math.max(1,Number(n)||1)}}).filter(x=>x.itemId);if(!d.contents.length)throw new Error("Bundle contents required");}}
