import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "../ui/ddui.js";
import * as Products from "../core/products.js";
import * as ItemTemplates from "../core/item_templates.js";
import { chooseItemTemplate } from "./item_template_editor.js";
import { LEGACY_PRODUCT_TEMPLATES } from "../data/legacy_product_templates.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
export function openProducts(player,{type}={}){const ps=Products.list({type}),pick=new ObservableNumber(0,{clientWritable:true}),info=new ObservableString(""),f=new CustomForm(player,type==="pet"?"Pet Shop":"Products & Services");const refresh=()=>{const p=ps[pick.getData()];info.setData(p?`${p.description??""}\nType: ${p.type}\nPrice: ${p.price} Moneyz`:"No products configured.")};pick.subscribe(refresh);refresh();if(ps.length)f.dropdown("Product",pick,ps.map((p,i)=>({label:p.name,value:i}))).label(info).button("Purchase",async()=>{const p=ps[pick.getData()],r=p&&await Products.purchase(player,p.id,{source:"product_ui"});player.sendMessage(r?.ok?`§aPurchased ${p.name}.`:`§cPurchase failed: ${r?.reason}`);nav(f,()=>openProducts(player,{type}));});else f.label("No products are configured.");f.button("Back",()=>nav(f,()=>import("./moneyz_menu.js").then(m=>m.main(player)))).closeButton().show();}
export function productAdmin(player){const ps=Products.all(),pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Product / Bundle Manager");if(ps.length)f.dropdown("Product",pick,ps.map((p,i)=>({label:`${p.name} • ${p.type} • ${p.price}`,value:i}))).button("Edit Selected",()=>nav(f,()=>edit(player,ps[pick.getData()])));f.button("Create Product",()=>nav(f,()=>chooseProductType(player))).button("Import Legacy Premium Products",()=>{const r=Products.importDefinitions(LEGACY_PRODUCT_TEMPLATES);player.sendMessage(`§aLegacy templates: ${r.added} added, ${r.skipped} already present.`);nav(f,()=>productAdmin(player));}).button("Back",()=>nav(f,()=>import("./admin_menu.js").then(m=>m.moneyzAdmin(player)))).closeButton().show();}

function chooseProductType(player){const types=["item","bundle","pet","entitlement","reservation","xp","legacy_structure"],pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Create Product");f.dropdown("Product Type",pick,types.map((x,i)=>({label:x,value:i}))).button("Continue",()=>nav(f,()=>edit(player,null,{type:types[pick.getData()]}))).button("Back",()=>nav(f,()=>productAdmin(player))).closeButton().show();}
function edit(player,p,draft){const types=["item","bundle","pet","entitlement","reservation","xp","legacy_structure"],base=draft??(p?JSON.parse(JSON.stringify(p)):{}),id=new ObservableString(base.id??"",{clientWritable:true}),name=new ObservableString(base.name??"",{clientWritable:true}),desc=new ObservableString(base.description??"",{clientWritable:true}),type=new ObservableNumber(Math.max(0,types.indexOf(base.type??"item")),{clientWritable:true}),price=new ObservableString(String(base.price??0),{clientWritable:true}),payload=new ObservableString(payloadText(base),{clientWritable:true}),f=new CustomForm(player,p?"Edit Product":"Create Product");f.textField("ID",id).textField("Name",name).textField("Description",desc).label(`Type: §f${base.type??"item"}`).textField("Price",price);
 const t=base.type??types[type.getData()];if(t==="item")f.label(base.itemTemplate?`§aExact item: ${ItemTemplates.describe(base.itemTemplate)}`:"§eNo exact item template configured yet.").button("Select / Configure Exact Item",()=>nav(f,()=>chooseItemTemplate(player,{title:"Product Item",initial:base.itemTemplate,onSave:(spec)=>edit(player,p,{...base,id:id.getData(),name:name.getData(),description:desc.getData(),type:"item",price:Number(price.getData()),itemTemplate:spec,itemId:spec.typeId,amount:spec.amount??1}),onBack:()=>edit(player,p,base)})));
 else if(t==="bundle")f.label(`§7${base.contents?.length??0} exact bundle entries configured.`).button("Manage Bundle Items",()=>nav(f,()=>bundleManager(player,p,{...base,id:id.getData(),name:name.getData(),description:desc.getData(),type:"bundle",price:Number(price.getData())})));
 else f.textField("Payload",payload,{description:"pet: entity id | entitlement: id | reservation: property id | xp: amount | legacy_structure: structure|position"});
 f.button("Save",()=>{try{const selected=base.type??"item",def={...base,id:id.getData(),name:name.getData(),description:desc.getData(),type:selected,price:Number(price.getData())};if(selected==="item"){if(!def.itemTemplate)throw new Error("Select/configure the exact item first");def.itemId=def.itemTemplate.typeId;def.amount=def.itemTemplate.amount??1;}else if(selected==="bundle"){if(!def.contents?.length)throw new Error("Add at least one bundle item");}else applyPayload(def,payload.getData());Products.upsert(def);player.sendMessage("§aProduct saved.");nav(f,()=>productAdmin(player));}catch(e){player.sendMessage(`§c${e}`)}});if(p)f.button("Delete",()=>{Products.remove(p.id);nav(f,()=>productAdmin(player));});f.button("Back",()=>nav(f,()=>productAdmin(player))).closeButton().show();}
function bundleManager(player,p,draft){const rows=draft.contents??[],pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Bundle Items");f.label(rows.length?rows.map((x,i)=>`${i+1}. ${x.itemTemplate?ItemTemplates.describe(x.itemTemplate):(x.itemId??x.id)} ×${x.amount??1}`).join("\n"):"§7No items yet.");f.button("Add Exact Item",()=>nav(f,()=>chooseItemTemplate(player,{title:"Bundle Item",onSave:(spec)=>bundleManager(player,p,{...draft,contents:[...rows,{type:"item",itemId:spec.typeId,amount:spec.amount??1,itemTemplate:spec}]}),onBack:()=>bundleManager(player,p,draft)})));if(rows.length)f.dropdown("Selected Entry",pick,rows.map((x,i)=>({label:x.itemTemplate?ItemTemplates.describe(x.itemTemplate):(x.itemId??x.id),value:i}))).button("Edit Selected Item",()=>{const i=pick.getData(),row=rows[i];nav(f,()=>chooseItemTemplate(player,{title:"Bundle Item",initial:row.itemTemplate??{version:1,typeId:row.itemId??row.id,amount:row.amount??1},onSave:(spec)=>{const next=[...rows];next[i]={type:"item",itemId:spec.typeId,amount:spec.amount??1,itemTemplate:spec};bundleManager(player,p,{...draft,contents:next});},onBack:()=>bundleManager(player,p,draft)}));}).button("Remove Selected",()=>{const i=pick.getData();nav(f,()=>bundleManager(player,p,{...draft,contents:rows.filter((_,n)=>n!==i)}));});f.button("Done",()=>nav(f,()=>edit(player,p,draft))).closeButton().show();}
function payloadText(p){if(!p)return "";if(p.type==="pet"||p.type==="entity")return p.entityId??"";if(p.type==="entitlement")return p.entitlementId??"";if(p.type==="reservation")return p.propertyId??"";if(p.type==="xp")return String(p.xp??5);if(p.type==="legacy_structure")return `${p.structureName??""}|${p.structurePosition??"~ ~ ~"}`;return "";}
function applyPayload(d,v){v=String(v??"").trim();if(d.type==="pet"){d.entityId=v;if(!v)throw new Error("Entity ID required");}else if(d.type==="entitlement"){d.entitlementId=v;if(!v)throw new Error("Entitlement ID required");}else if(d.type==="reservation"){d.propertyId=v;if(!v)throw new Error("Hotel property ID required");}else if(d.type==="xp"){d.xp=Math.max(1,Number(v)||1);}else if(d.type==="legacy_structure"){const [structureName,structurePosition]=v.split("|");d.structureName=structureName?.trim();d.structurePosition=structurePosition?.trim()||"~ ~ ~";if(!d.structureName)throw new Error("Structure name required");}}
