import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "../ui/ddui.js";
import * as Properties from "../core/properties.js";
import { LEGACY_MSV_PROPERTIES } from "../data/legacy_property_templates.js";
import { main } from "./moneyz_menu.js";
const nav=(f,fn)=>{try{if(f.isShowing())f.close();}catch{}system.run(fn)};
export function openProperties(player,{type}={}){const st=Properties.status(player),f=new CustomForm(player,type==="hotel"?"Hotel Services":"Property Services");f.header(type==="hotel"?"Hotel Services":"Real Estate").label(`Owned: ${st.owned.length}\nRented: ${st.rented.length}`);f.button(type==="hotel"?"Available Rooms":"Available Properties",()=>nav(f,()=>browse(player,type))).button("My Properties / Rentals",()=>nav(f,()=>mine(player)));f.button("Back",()=>nav(f,()=>main(player))).closeButton().show();}
function browse(player,type){const props=Properties.list({type,available:true}).filter(p=>p.enabled!==false),pick=new ObservableNumber(0,{clientWritable:true}),info=new ObservableString(""),f=new CustomForm(player,"Available Properties");const refresh=()=>{const p=props[pick.getData()];info.setData(p?`${p.description??""}\nType: ${p.type}\nBuy: ${p.type==="hotel"?"N/A":p.price+" Moneyz"}\nRent: ${p.rent} Moneyz / ${Math.round(p.rentInterval/3600)}h`:"No properties available.")};pick.subscribe(refresh);refresh();if(props.length)f.dropdown("Property",pick,props.map((p,i)=>({label:p.name,value:i}))).label(info).button("Buy",()=>{const p=props[pick.getData()],r=p&&Properties.buy(player,p.id);player.sendMessage(r?.ok?`§aPurchased ${p.name}.`:`§cPurchase failed: ${r?.reason}.`);nav(f,()=>openProperties(player,{type}));}).button("Rent / Book",()=>{const p=props[pick.getData()],r=p&&Properties.rent(player,p.id);player.sendMessage(r?.ok?`§aRented ${p.name}.`:`§cRental failed: ${r?.reason}.`);nav(f,()=>openProperties(player,{type}));});else f.label("No available properties.");f.button("Back",()=>nav(f,()=>openProperties(player,{type}))).closeButton().show();}
function mine(player){const all=[...Properties.ownedBy(player).map(p=>({p,kind:"owned"})),...Properties.rentedBy(player).map(p=>({p,kind:"rented"}))],pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"My Properties");if(all.length)f.dropdown("Property",pick,all.map((x,i)=>({label:`${x.p.name} • ${x.kind}`,value:i}))).button("Manage",()=>nav(f,()=>manage(player,all[pick.getData()])));else f.label("You do not own or rent any properties.");f.button("Back",()=>nav(f,()=>openProperties(player))).closeButton().show();}
function manage(player,x){if(!x)return mine(player);const {p,kind}=x,f=new CustomForm(player,p.name);f.label(`Type: ${p.type}\n${kind==="owned"?`Owned • resale ${p.price} Moneyz`:`Rent: ${p.rent} Moneyz\nNext due: ${p.nextRentAt?new Date(p.nextRentAt).toLocaleString():"N/A"}`}`);if(kind==="owned")f.button("Sell Property",()=>{const r=Properties.sell(player,p.id);player.sendMessage(r.ok?`§aSold for ${r.amount} Moneyz.`:`§cSale failed: ${r.reason}`);nav(f,()=>mine(player));});else f.button("Pay Rent",()=>{const r=Properties.payRent(player,p.id);player.sendMessage(r.ok?`§aPaid ${r.amount} Moneyz rent.`:`§eRent payment: ${r.reason}`);nav(f,()=>manage(player,{p:Properties.get(p.id),kind}));}).button("Check Out / End Rental",()=>{Properties.checkout(player,p.id);nav(f,()=>mine(player));});f.button("Back",()=>nav(f,()=>mine(player))).closeButton().show();}
export function propertyAdmin(player){const props=Properties.list(),pick=new ObservableNumber(0,{clientWritable:true}),f=new CustomForm(player,"Property Manager");if(props.length)f.dropdown("Existing property",pick,props.map((p,i)=>({label:`${p.name} • ${p.type}`,value:i}))).button("Edit Selected",()=>nav(f,()=>edit(player,props[pick.getData()])));f.button("Create Property / Room",()=>nav(f,()=>edit(player,null))).button("Import Legacy MSV Property Template",()=>{const r=Properties.importDefinitions(LEGACY_MSV_PROPERTIES);player.sendMessage(`§aLegacy property template: ${r.added} added, ${r.skipped} already present. Existing worlds migrate ownership tags as players join.`);nav(f,()=>propertyAdmin(player));}).button("Back",()=>nav(f,()=>import("./admin_menu.js").then(m=>m.moneyzAdmin(player)))).closeButton().show();}
function edit(player,p){const id=new ObservableString(p?.id??"",{clientWritable:true}),name=new ObservableString(p?.name??"",{clientWritable:true}),desc=new ObservableString(p?.description??"",{clientWritable:true}),type=new ObservableNumber(["residential","hotel","commercial"].indexOf(p?.type??"residential"),{clientWritable:true}),price=new ObservableString(String(p?.price??0),{clientWritable:true}),rent=new ObservableString(String(p?.rent??0),{clientWritable:true}),interval=new ObservableString(String(p?.rentInterval??86400),{clientWritable:true}),f=new CustomForm(player,p?"Edit Property":"Create Property");f.textField("Property ID",id).textField("Name",name).textField("Description",desc).dropdown("Type",type,[{label:"Residential",value:0},{label:"Hotel",value:1},{label:"Commercial",value:2}]).textField("Purchase price",price).textField("Rent / booking price",rent).textField("Rent interval seconds",interval).button("Save",()=>{try{Properties.upsert({id:id.getData(),name:name.getData(),description:desc.getData(),type:["residential","hotel","commercial"][type.getData()],price:Number(price.getData()),rent:Number(rent.getData()),rentInterval:Number(interval.getData())});player.sendMessage("§aProperty saved.");nav(f,()=>propertyAdmin(player));}catch(e){player.sendMessage(`§c${e}`)}});if(p)f.button("Delete",()=>{Properties.remove(p.id);nav(f,()=>propertyAdmin(player));});f.button("Back",()=>nav(f,()=>propertyAdmin(player))).closeButton().show();}
