import { world } from "@minecraft/server";
import { ActionFormData } from "../ui/forms.js";
import { main } from "./moneyz_menu.js";
import { getCurrentUTCDate } from "../utilities.js";
import * as Quests from "../quest/engine.js";
import { log, LOG_LEVELS } from "../logger.js";

const WORLD_SEED_PROPERTY="dailyQuestSeed",WORLD_SEED_DATE_PROPERTY="lastQuestSeedDate";
function getDailySeed(){let seed=world.getDynamicProperty(WORLD_SEED_PROPERTY),date=world.getDynamicProperty(WORLD_SEED_DATE_PROPERTY);const today=getCurrentUTCDate();if(seed===undefined||date!==today){seed=Math.random().toString(36).slice(2);world.setDynamicProperty(WORLD_SEED_PROPERTY,seed);world.setDynamicProperty(WORLD_SEED_DATE_PROPERTY,today);}return String(seed);}
function hash(s){let h=0;for(let i=0;i<s.length;i++){h=(h<<5)-h+s.charCodeAt(i);h|=0;}return h;}
function dailyQuests(list,count=3){const seed=getDailySeed();const score=q=>{const n=hash(seed+q.id);return Math.abs(n%1000000);};const byType=new Map();for(const q of list){const cur=byType.get(q.objective.type);if(!cur||score(q)>score(cur))byType.set(q.objective.type,q);}return [...byType.values()].sort((a,b)=>score(b)-score(a)).slice(0,count);}
function progressText(active){const q=active,state=active.state,p=state.progress,o=q.objective;if(["break","plant","slay","slaughter"].includes(o.type))return `${p.current}/${p.target}`;if(o.type==="location")return `${Math.round(p.distance)}/${p.target} blocks`;if(o.type==="maintain_balance"){const left=Math.max(0,p.target-p.elapsed);return `${Math.floor(left/60000)}m ${Math.floor((left%60000)/1000)}s remaining`;}return "In progress";}
function rewardText(q){const r=q.reward;if(r.type==="Moneyz")return `${r.amount} Moneyz`;if(r.type==="experience")return `${r.amount} XP`;if(r.type==="item")return `${r.itemStack?.amount??1} ${r.itemStack?.typeId??"item"}`;return r.type;}
export function giveQuest(player,isNpcInteraction=false){if(!player)return;const active=Quests.getActiveQuest(player);const form=new ActionFormData().title("§l§1Quest Journal");if(active){form.body(`§l§fACTIVE QUEST\n\n§a${active.description}\n§fProgress: §e${progressText(active)}\n§fCompletion Reward: §e${rewardText(active)}\n\n§7Progress rewards are paid as you work.`).button("Abandon Quest");}
else{const available=dailyQuests(Quests.getAvailable(player).filter(q=>!Quests.isCompletedToday(player,q)),3);form.body(available.length?`§l§fTODAY'S QUESTS\n\n${available.map((q,i)=>`§7${i+1}. §f${q.description}\n   §eReward: ${rewardText(q)}`).join("\n\n")}`:"§7No eligible quests remain today.");for(const q of available)form.button(q.description);form._moneyzQuestChoices=available;}
form.button("Back");form.show(player).then(r=>{if(!r||r.canceled||r.selection===undefined)return;if(active){if(r.selection===0)return confirmAbandon(player,active,isNpcInteraction);if(r.selection===1&&!isNpcInteraction)main(player);return;}const choices=form._moneyzQuestChoices??[];if(r.selection===choices.length){if(!isNpcInteraction)main(player);return;}const q=choices[r.selection];if(!q)return;const result=Quests.startQuest(player,q.id);if(result.ok){player.sendMessage(`§aQuest accepted: ${q.description}`);giveQuest(player,isNpcInteraction);return;}const messages={daily_limit:"§cThat quest has already been completed today.",active_quest:"§cYou already have an active quest.",patrol_unconfigured:"§cPatrol location is not configured.",insufficient_balance:`§cYou need at least ${q.objective.amount} Moneyz to start this quest.`,peaceful_difficulty:"§eHostile-mob quests are unavailable while the world is on Peaceful difficulty."};player.sendMessage(messages[result.reason]??"§cUnable to start that quest.");}).catch(e=>log(`Quest Journal error: ${e}`,LOG_LEVELS.ERROR));}
function confirmAbandon(player,active,isNpc){new ActionFormData().title("§l§1Abandon Quest?").body(`§fAbandon §e${active.description}§f?\n\n§7Current progress will be lost.`).button("Abandon Quest").button("Keep Quest").show(player).then(r=>{if(!r||r.canceled)return;if(r.selection===0){Quests.abandonQuest(player);player.sendMessage("§eQuest abandoned.");}else giveQuest(player,isNpc);});}
// Compatibility exports for older bundled integrations.
export const getActiveQuest=Quests.getActiveQuest;
export const completeQuest=Quests.completeActiveQuest;
log("quest_menu.js loaded",LOG_LEVELS.DEBUG);
