import { system } from "@minecraft/server";
import { CustomForm, ObservableNumber, ObservableString } from "@minecraft/server-ui";
import * as Shops from "../repositories/shops.js";
import * as Commerce from "../services/commerce.js";
import * as Inventory from "../services/inventory.js";
import * as Economy from "../core/economy.js";
import * as Permissions from "../core/permissions.js";
const nav=(form,fn)=>{try{if(form.isShowing())form.close();}catch{}system.run(fn);};
const pretty=s=>String(s??"").replace(/^minecraft:/,"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
export function openShop(player,shopId,{isNpcInteraction=false,source="direct"}={}){const shop=Shops.getShop(shopId);if(!shop||shop.enabled===false){player.sendMessage("§cThat shop is unavailable.");return;}if(shop.settings?.permission&&!Permissions.has(player,shop.settings.permission)){player.sendMessage("§cYou do not have permission to use this shop.");return;}if(isNpcInteraction&&shop.settings?.allowNpcBinding===false){player.sendMessage("§cThis shop is not available through NPCs.");return;}if(!isNpcInteraction&&source!=="browser"&&shop.settings?.allowDirectAccess===false){player.sendMessage("§cDirect access to this shop is disabled.");return;}const cats=Shops.categories(shopId);if(!cats.length){player.sendMessage("§cThis shop has no listings.");return;}const cat=new ObservableNumber(0,{clientWritable:true});const form=new CustomForm(player,shop.name??pretty(shopId));form.label(`§6Balance: §g${Economy.getBalance(player)} Moneyz`).dropdown("Category",cat,cats.map((x,i)=>({label:pretty(x),value:i}))).button("Browse",()=>nav(form,()=>openCategory(player,shopId,cats[cat.getData()]??cats[0],{isNpcInteraction}))).button("Back",()=>nav(form,()=>import("./moneyz_menu.js").then(m=>m.main(player)))).closeButton().show();}
function openCategory(player,shopId,category,ctx){const rows=Shops.listListings(shopId,{category,enabledOnly:true});const idx=new ObservableNumber(0,{clientWritable:true});const form=new CustomForm(player,pretty(category));if(!rows.length){form.label("No listings in this category.").button("Back",()=>nav(form,()=>openShop(player,shopId,ctx))).closeButton().show();return;}form.dropdown("Item",idx,rows.map((x,i)=>({label:x.name,value:i}))).button("Open Listing",()=>nav(form,()=>openListing(player,shopId,rows[idx.getData()]?.id,ctx))).button("Back",()=>nav(form,()=>openShop(player,shopId,ctx))).closeButton().show();}
function openListing(player,shopId,listingId,ctx){const shop=Shops.getShop(shopId),x=Shops.getListing(shopId,listingId);if(!x)return openShop(player,shopId,ctx);const maxSell=Math.floor(Inventory.count(player,x.typeId)/Math.max(1,x.sell.amount));const qty=new ObservableNumber(1,{clientWritable:true});const status=new ObservableString(`§6Balance: §g${Economy.getBalance(player)} Moneyz\n§fYou have: ${Inventory.count(player,x.typeId)}\n${x.stock.mode==="unlimited"?"§7Stock: Unlimited":`§7Stock: ${x.stock.quantity}`}`);const form=new CustomForm(player,x.name);form.header("Prices").label(`${x.buy.enabled?`§aBUY  §f${x.buy.amount} for §g${x.buy.price} Moneyz`:"§7BUY  Disabled"}\n${x.sell.enabled?`§eSELL §f${x.sell.amount} for §g${x.sell.price} Moneyz`:"§7SELL Disabled"}`).divider().label(status).slider("Quantity",qty,1,64,{step:1,description:"Number of listing bundles"});if(x.buy.enabled)form.button(`BUY • ${x.buy.price} Moneyz / bundle`,async()=>{const r=await Commerce.buyListing(player,shopId,listingId,qty.getData());status.setData(r.ok?`§aPurchased ${r.amount} ${x.name} for ${r.total} Moneyz.`:`§cPurchase failed: ${r.reason}`);});if(x.sell.enabled)form.button(`SELL • ${x.sell.price} Moneyz / bundle`,async()=>{const r=await Commerce.sellListing(player,shopId,listingId,qty.getData());status.setData(r.ok?`§aSold ${r.amount} ${x.name} for ${r.total} Moneyz.`:`§cSale failed: ${r.reason}`);});if(x.sell.enabled&&maxSell>0)form.button(`SELL ALL • ${maxSell} bundles`,async()=>{const r=await Commerce.sellListing(player,shopId,listingId,maxSell);status.setData(r.ok?`§aSold ${r.amount} ${x.name} for ${r.total} Moneyz.`:`§cSale failed: ${r.reason}`);});form.button("Back",()=>nav(form,()=>openCategory(player,shopId,x.category,ctx))).closeButton().show();}
