import { system } from "@minecraft/server";
import { ActionFormData } from "../ui/forms.js";
import { CustomForm, ObservableNumber, ObservableString } from "@minecraft/server-ui";
import { getShopData, saveShop, deleteShop } from "../data_provider.js";
import { moneyzAdmin } from "./admin_menu.js";
import { log, LOG_LEVELS } from "../logger.js";
const display=id=>id.replace(/_/g," ").replace(/\b\w/g,l=>l.toUpperCase());
const navigate=(form,next)=>{try{if(form.isShowing())form.close();}catch{} system.run(next);};
export function showShopEditorMenu(player){if(!player)return;new ActionFormData().title("§l§1Shop Editor").body("§oManage your world's shops.").button("Create New Shop").button("Open Shop Editor").button("Remove Shop").button("Back").show(player).then(r=>{if(r.canceled)return;if(r.selection===0)createShop(player);else if(r.selection===1)selectShop(player);else if(r.selection===2)removeShop(player);else moneyzAdmin(player);}).catch(e=>log(`Shop editor: ${e}`,LOG_LEVELS.ERROR));}
function createShop(player){
 const id=new ObservableString("",{clientWritable:true}); const form=new CustomForm(player,"§l§1Create Shop");
 form.textField("Shop ID (lowercase, no spaces)",id).button("Create",()=>{const v=id.getData().trim();if(!v||/\s/.test(v)||v!==v.toLowerCase()){player.sendMessage("§cInvalid shop ID.");return;}if(getShopData()[v]){player.sendMessage("§cThat shop already exists.");return;}saveShop(v,{});player.sendMessage(`§aCreated ${v}.`);navigate(form,()=>openEditor(player,v));}).button("Back",()=>navigate(form,()=>showShopEditorMenu(player))).closeButton().show();
}
function selectShop(player){
 const ids=Object.keys(getShopData());if(!ids.length){player.sendMessage("§cNo shops available.");return showShopEditorMenu(player);}const selected=new ObservableNumber(0,{clientWritable:true});const form=new CustomForm(player,"§l§1Select Shop");
 form.dropdown("Shop",selected,ids.map((id,i)=>({label:display(id),value:i}))).button("Open",()=>navigate(form,()=>openEditor(player,ids[selected.getData()]))).button("Back",()=>navigate(form,()=>showShopEditorMenu(player))).closeButton().show();
}
function openEditor(player,shopId){const shop=getShopData()[shopId]??{},categories=Object.keys(shop);const category=new ObservableNumber(0,{clientWritable:true}),itemIndex=new ObservableNumber(0,{clientWritable:true});const itemId=new ObservableString("",{clientWritable:true}),name=new ObservableString("",{clientWritable:true}),amount=new ObservableString("1",{clientWritable:true}),buy=new ObservableString("0",{clientWritable:true}),sell=new ObservableString("0",{clientWritable:true}),buyData=new ObservableString("0",{clientWritable:true}),sellData=new ObservableString("0",{clientWritable:true}),icon=new ObservableString("",{clientWritable:true}),status=new ObservableString("§7Select an item or enter values for a new item.");
 const currentCategory=()=>categories[category.getData()]??categories[0]; const rows=()=>shop[currentCategory()]??[]; const load=()=>{const x=rows()[itemIndex.getData()];if(!x){status.setData("§7New item mode.");return;}itemId.setData(x.id??"");name.setData(x.name??"");amount.setData(String(x.amount??1));buy.setData(String(x.buyPrice??0));sell.setData(String(x.sellPrice??0));buyData.setData(String(x.buyDamage??0));sellData.setData(String(x.sellDamage??0));icon.setData(x.iconPath??"");status.setData(`§aEditing ${x.name}`);}; category.subscribe(()=>{itemIndex.setData(0);load();});itemIndex.subscribe(load);load();
 const form=new CustomForm(player,`§l§1Shop: ${shopId}`).label(status);if(categories.length)form.dropdown("Category",category,categories.map((id,i)=>({label:display(id),value:i}))).dropdown("Item",itemIndex,(rows().length?rows():[{name:"<new item>"}]).map((x,i)=>({label:x.name??x.id??`Item ${i+1}`,value:i})));
 form.textField("Item ID",itemId).textField("Display Name",name).textField("Amount",amount).textField("Buy Price (-1 disables)",buy).textField("Sell Price (-1 disables)",sell).textField("Buy Data",buyData).textField("Sell Data",sellData).textField("Icon Path",icon)
 .button("Save / Add",()=>{let cat=currentCategory();if(!cat){player.sendMessage("§cCreate a category first.");return;}const x={id:itemId.getData().trim(),name:name.getData().trim(),amount:Math.max(1,parseInt(amount.getData(),10)||1),buyPrice:parseInt(buy.getData(),10),sellPrice:parseInt(sell.getData(),10),buyDamage:parseInt(buyData.getData(),10)||0,sellDamage:parseInt(sellData.getData(),10)||0,iconPath:icon.getData().trim()||undefined};if(!x.id||!x.name){player.sendMessage("§cItem ID and name are required.");return;}if(!Number.isFinite(x.buyPrice))x.buyPrice=0;if(!Number.isFinite(x.sellPrice))x.sellPrice=0;shop[cat]??=[];const idx=itemIndex.getData();if(shop[cat][idx])shop[cat][idx]=x;else shop[cat].push(x);saveShop(shopId,shop);player.sendMessage(`§aSaved ${x.name}.`);})
 .button("New Category",()=>navigate(form,()=>newCategory(player,shopId,shop))).button("New Item",()=>{itemIndex.setData(rows().length);itemId.setData("");name.setData("");amount.setData("1");buy.setData("0");sell.setData("0");status.setData("§7New item mode.");})
 .button("Delete Selected Item",()=>{const cat=currentCategory(),idx=itemIndex.getData();if(cat&&shop[cat]?.[idx]){const removed=shop[cat].splice(idx,1)[0];if(!shop[cat].length)delete shop[cat];saveShop(shopId,shop);player.sendMessage(`§eRemoved ${removed.name}. Reopen editor to refresh lists.`);}}).button("Back",()=>navigate(form,()=>selectShop(player))).closeButton();form.show();}
function newCategory(player,shopId,shop){
 const id=new ObservableString("",{clientWritable:true});const form=new CustomForm(player,"§l§1New Category");
 form.textField("Category ID",id).button("Create",()=>{const v=id.getData().trim();if(!v||/\s/.test(v)||v!==v.toLowerCase()||shop[v]){player.sendMessage("§cInvalid or duplicate category.");return;}shop[v]=[];saveShop(shopId,shop);player.sendMessage(`§aCreated ${v}. Reopen editor to select it.`);}).button("Back",()=>navigate(form,()=>openEditor(player,shopId))).closeButton().show();
}
function removeShop(player){
 const ids=Object.keys(getShopData());if(!ids.length)return showShopEditorMenu(player);const selected=new ObservableNumber(0,{clientWritable:true});const form=new CustomForm(player,"§l§cRemove Shop");
 form.dropdown("Shop",selected,ids.map((id,i)=>({label:display(id),value:i}))).button("Delete",()=>{const id=ids[selected.getData()];deleteShop(id);player.sendMessage(`§eRemoved ${id}.`);navigate(form,()=>showShopEditorMenu(player));}).button("Back",()=>navigate(form,()=>showShopEditorMenu(player))).closeButton().show();
}
log("shop_editor.js loaded",LOG_LEVELS.DEBUG);
