import { world } from "@minecraft/server";
import { log, LOG_LEVELS } from "../logger.js";
import { record } from "./transactions.js";
import { emit, emitCancelable } from "./events.js";
import { authorize } from "./policies.js";

const OBJECTIVE="Moneyz";
function objective(){return world.scoreboard.getObjective(OBJECTIVE);}
const integer=v=>Math.round(Number(v));
export function isReady(){return Boolean(objective());}
export function getBalance(target,useZero=true){const obj=objective();if(!obj||!target)return useZero?0:NaN;try{let score;if(typeof target==="string"){const p=world.scoreboard.getParticipants().find(x=>x.displayName===target);score=p?obj.getScore(p):obj.getScore(target);}else score=obj.getScore(target);return score!==undefined?score:(useZero?0:NaN);}catch{return useZero?0:NaN;}}
function commit(type,{player,actor,from,to,amount,before,after,metadata}){const tx=record(type,{actor,from,to,amount,balanceBefore:before,balanceAfter:after,metadata});emit("balanceChanged",{player,before,after,delta:after-before,transaction:tx});return tx;}
export function setBalance(player,amount,metadata={}){const value=integer(amount);if(!player||!Number.isFinite(value))return false;const obj=objective();if(!obj){log("Economy: Moneyz objective not found.",LOG_LEVELS.ERROR);return false;}try{const before=getBalance(player);obj.setScore(player,value);commit(metadata.type??"set",{player,actor:metadata.actor,to:player,amount:value,before,after:value,metadata});return true;}catch(e){log(`Economy.setBalance failed: ${e}`,LOG_LEVELS.ERROR);return false;}}
export function canAfford(player,amount){return getBalance(player)>=Math.max(0,integer(amount));}
export function deposit(player,amount,metadata={}){const value=integer(amount);if(!player||!Number.isFinite(value)||value<0)return false;const policy=authorize({operation:"deposit",player,amount:value,metadata});if(!policy.allowed)return false;const gate=emitCancelable("beforeTransaction",{operation:"deposit",player,amount:value,metadata});if(gate.cancel)return false;const obj=objective();if(!obj)return false;try{const before=getBalance(player);obj.addScore(player,value);commit(metadata.type??"deposit",{player,actor:metadata.actor,to:player,amount:value,before,after:before+value,metadata});return true;}catch(e){log(`Economy.deposit failed: ${e}`,LOG_LEVELS.ERROR);return false;}}
export function withdraw(player,amount,metadata={}){const value=integer(amount);if(!player||!Number.isFinite(value)||value<0)return false;const policy=authorize({operation:"withdraw",player,amount:value,metadata});if(!policy.allowed)return false;const gate=emitCancelable("beforeTransaction",{operation:"withdraw",player,amount:value,metadata});if(gate.cancel)return false;const before=getBalance(player,false);if(!Number.isFinite(before)||before<value)return false;const obj=objective();if(!obj)return false;try{obj.addScore(player,-value);commit(metadata.type??"withdraw",{player,actor:metadata.actor,from:player,amount:value,before,after:before-value,metadata});return true;}catch(e){log(`Economy.withdraw failed: ${e}`,LOG_LEVELS.ERROR);return false;}}
export function transfer(from,to,amount,metadata={}){const value=integer(amount);if(!from||!to||from===to||!Number.isFinite(value)||value<=0)return false;const policy=authorize({operation:"transfer",from,to,amount:value,metadata});if(!policy.allowed)return false;const gate=emitCancelable("beforeTransfer",{from,to,amount:value,metadata});if(gate.cancel)return false;const obj=objective(),fromBefore=getBalance(from,false),toBefore=getBalance(to,false);if(!obj||!Number.isFinite(fromBefore)||fromBefore<value||!Number.isFinite(toBefore))return false;try{obj.addScore(from,-value);try{obj.addScore(to,value);}catch(e){obj.addScore(from,value);throw e;}const tx=record(metadata.type??"transfer",{actor:metadata.actor??from,from,to,amount:value,balanceBefore:fromBefore,balanceAfter:fromBefore-value,metadata:{...metadata,toBalanceBefore:toBefore,toBalanceAfter:toBefore+value}});emit("balanceChanged",{player:from,before:fromBefore,after:fromBefore-value,delta:-value,transaction:tx});emit("balanceChanged",{player:to,before:toBefore,after:toBefore+value,delta:value,transaction:tx});return true;}catch(e){log(`Economy.transfer failed: ${e}`,LOG_LEVELS.ERROR);return false;}}
