import * as Shops from "../repositories/shops.js";
import * as Economy from "./economy.js";
import * as Treasury from "./treasury.js";
import * as Inventory from "../services/inventory.js";
import * as Products from "./products.js";
import * as Config from "./config.js";

const csv=v=>String(v??"").split(",").map(x=>x.trim()).filter(Boolean);
export function getConfig(){return {price:Math.max(0,Config.number("luckyPurchasePrice",150)),useStock:Config.bool("luckyUseShopStock",true),shops:csv(Config.get("luckyShops","")),categories:csv(Config.get("luckyCategories","")),minValue:Math.max(0,Config.number("luckyMinValue",0)),maxValue:Math.max(0,Config.number("luckyMaxValue",0))};}
export function eligibleProducts(options={}){const cfg={...getConfig(),...options},shopFilter=new Set(cfg.shops??[]),catFilter=new Set(cfg.categories??[]),rows=[];for(const [shopId,shop] of Object.entries(Shops.getShopData())){if(shop.enabled===false||shop.settings?.allowBuy===false)continue;if(shopFilter.size&&!shopFilter.has(shopId))continue;for(const listing of shop.listings??[]){if(listing.enabled===false||!listing.buy?.enabled)continue;if(listing.lucky?.enabled===false)continue;if(catFilter.size&&!catFilter.has(listing.category??"general"))continue;const value=Math.max(0,Number(listing.buy.price)||0),amount=Math.max(1,Number(listing.buy.amount)||1);if(cfg.minValue&&value<cfg.minValue)continue;if(cfg.maxValue&&value>cfg.maxValue)continue;const unlimited=listing.stock?.mode==="unlimited";const stock=unlimited?Infinity:Math.max(0,Number(listing.stock?.quantity)||0);if(cfg.useStock!==false&&!unlimited&&stock<1)continue;rows.push({shopId,shopName:shop.name,listingId:listing.id,category:listing.category??"general",typeId:listing.typeId,name:listing.name,value,amount,stock:unlimited?-1:stock,unlimitedStock:unlimited,weight:Math.max(0.0001,Number(listing.lucky?.weight)||1),productId:listing.productId??null});}}return rows;}
export function calculateWeight(product,price=getConfig().price){const explicit=Number(product?.weight);if(Number.isFinite(explicit)&&explicit!==1)return Math.max(0.0001,explicit);const value=Math.max(1,Number(product?.value)||1),p=Math.max(1,Number(price)||1);return Math.max(0.05,Math.min(5,p/value));}
export function roll(options={}){const cfg={...getConfig(),...options},rows=eligibleProducts(cfg);if(!rows.length)return {ok:false,reason:"no_eligible_products"};let total=0;const weighted=rows.map(product=>{const weight=calculateWeight(product,cfg.price);total+=weight;return {product,weight};});let n=Math.random()*total;for(const row of weighted){n-=row.weight;if(n<=0)return {ok:true,product:row.product,price:cfg.price,eligible:rows.length};}return {ok:true,product:weighted[weighted.length-1].product,price:cfg.price,eligible:rows.length};}
export async function purchase(player,options={}){if(!player)return {ok:false,reason:"player_required"};const cfg={...getConfig(),...options},price=Math.max(0,Number(cfg.price)||0),r=roll(cfg);if(!r.ok)return r;const p=r.product,listing=Shops.getListing(p.shopId,p.listingId);if(!listing||listing.enabled===false||!listing.buy?.enabled)return {ok:false,reason:"product_unavailable"};if(cfg.useStock!==false&&listing.stock?.mode!=="unlimited"&&(listing.stock?.quantity??0)<1)return {ok:false,reason:"out_of_stock"};if(Economy.getBalance(player)<price)return {ok:false,reason:"insufficient_funds",price};
 // Reserve one listing unit before money/item mutation so Lucky and normal Shop purchases share one stock source.
 let reserved=false;if(cfg.useStock!==false&&listing.stock?.mode!=="unlimited"){Shops.adjustStock(p.shopId,p.listingId,-1);reserved=true;}
 if(!Economy.withdraw(player,price,{type:"lucky_purchase",source:"shop_catalog",shopId:p.shopId,listingId:p.listingId,itemId:p.typeId,itemAmount:p.amount})){if(reserved)Shops.adjustStock(p.shopId,p.listingId,1);return {ok:false,reason:"charge_failed"};}
 let delivered=false,reason="delivery_failed";try{if(listing.productId){const def=Products.get(listing.productId);if(def){const dr=await Products.deliver(player,def,{source:"lucky_purchase",shopId:p.shopId,listingId:p.listingId});delivered=!!dr?.ok;reason=dr?.reason??reason;}else reason="unknown_product";}else delivered=listing.itemTemplate?await Inventory.giveTemplate(player,listing.itemTemplate,p.amount):await Inventory.give(player,p.typeId,p.amount,listing.legacy?.buyDamage??0);}catch(e){reason="delivery_failed";}
 if(!delivered){Economy.deposit(player,price,{type:"lucky_purchase_refund",source:"shop_catalog"});if(reserved)Shops.adjustStock(p.shopId,p.listingId,1);return {ok:false,reason,price};}
 Treasury.collect(price,{type:"lucky_purchase",shopId:p.shopId,listingId:p.listingId});return {ok:true,price,product:p,value:p.value,shopId:p.shopId,listingId:p.listingId};}
export function preview(count=10,options={}){const out=[];for(let i=0;i<Math.max(1,Math.min(1000,Number(count)||10));i++){const r=roll(options);if(!r.ok)return r;out.push(r.product);}return {ok:true,count:out.length,products:out};}
