import { safeEntityName } from "./entity_identity.js";
import * as Storage from "./storage.js";
import * as Economy from "./economy.js";
import * as Treasury from "./treasury.js";
import { emit } from "./events.js";
const db=Storage.namespace("properties");const KEY="listings";
const clean=v=>String(v??"").trim().toLowerCase().replace(/[^a-z0-9_.-]/g,"_");
function load(){const v=db.get(KEY);return Array.isArray(v)?v:[];}function save(v){db.set(KEY,v);return v;}
export function list({type,available}={}){return load().filter(x=>(!type||x.type===type)&&(available===undefined||Boolean(!x.owner&&!x.tenant)===available));}
export function get(id){return load().find(x=>x.id===clean(id))??null;}
export function upsert(def){const a=load(),id=clean(def.id||def.name);if(!id)throw new Error("Property id required");const i=a.findIndex(x=>x.id===id),old=i>=0?a[i]:{};const p={...old,...def,id,name:String(def.name??old.name??id),type:["residential","hotel","commercial"].includes(def.type)?def.type:(old.type??"residential"),price:Math.max(0,Math.round(Number(def.price??old.price??0))),rent:Math.max(0,Math.round(Number(def.rent??old.rent??0))),rentInterval:Math.max(60,Math.round(Number(def.rentInterval??old.rentInterval??86400))),enabled:def.enabled!==false,provider:String(def.provider??old.provider??"world"),metadata:{...(old.metadata??{}),...(def.metadata??{})},access:{...(old.access??{}),...(def.access??{})}};if(i>=0)a[i]=p;else a.push(p);save(a);emit("propertyChanged",{property:p});return p;}
export function importDefinitions(defs,{overwrite=false}={}){let added=0,updated=0,skipped=0;for(const def of defs??[]){const old=get(def?.id);if(old&&!overwrite){skipped++;continue;}upsert(def);old?updated++:added++;}return {ok:true,added,updated,skipped};}
export const exportDefinitions=()=>load().map(x=>({...x}));
export function migrateLegacyPlayer(player){const a=load();let changed=0;for(let i=0;i<a.length;i++){const p=a[i],tag=p.legacyTag;if(!tag||p.owner||!player?.hasTag?.(tag))continue;p.owner=who(player);p.purchasedAt=p.purchasedAt??Date.now();a[i]=p;changed++;}if(changed)save(a);return {ok:true,changed};}
export function remove(id){const a=load(),n=a.filter(x=>x.id!==clean(id));if(n.length===a.length)return false;save(n);return true;}
const who=p=>safeEntityName(p,typeof p==="string"?p:"");
export function ownedBy(player){const n=who(player);return load().filter(x=>x.owner===n);}
export function rentedBy(player){const n=who(player);return load().filter(x=>x.tenant===n);}
export function buy(player,id){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i];if(p.type==="hotel")return {ok:false,reason:"not_for_sale"};if(p.owner||p.tenant)return {ok:false,reason:"unavailable"};if(!Economy.withdraw(player,p.price,{type:"property_purchase",propertyId:p.id}))return {ok:false,reason:"insufficient_funds"};Treasury.collect(p.price,{type:"property_purchase",propertyId:p.id});p.owner=who(player);p.purchasedAt=Date.now();a[i]=p;save(a);emit("propertyPurchased",{player,property:p});return {ok:true,property:p};}
export function sell(player,id,{rate=1}={}){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i];if(p.owner!==who(player))return {ok:false,reason:"not_owner"};const amount=Math.max(0,Math.round(p.price*rate));if(amount){const pay=Treasury.payout(amount,{type:"property_sale",propertyId:p.id});if(!pay.ok)return {ok:false,reason:pay.reason,required:amount,available:pay.balance};if(!Economy.deposit(player,amount,{type:"property_sale",propertyId:p.id})){Treasury.collect(amount,{type:"property_sale_rollback",propertyId:p.id});return {ok:false,reason:"payout_failed"};}}p.owner=undefined;p.purchasedAt=undefined;a[i]=p;save(a);emit("propertySold",{player,property:p,amount});return {ok:true,property:p,amount};}
export function rent(player,id){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i];if(p.owner||p.tenant)return {ok:false,reason:"unavailable"};if(!Economy.withdraw(player,p.rent,{type:p.type==="hotel"?"hotel_rent":"property_rent",propertyId:p.id}))return {ok:false,reason:"insufficient_funds"};Treasury.collect(p.rent,{type:"property_rent",propertyId:p.id});p.tenant=who(player);p.rentedAt=Date.now();p.nextRentAt=Date.now()+p.rentInterval*1000;a[i]=p;save(a);emit("propertyRented",{player,property:p});return {ok:true,property:p};}
export function payRent(player,id){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i];if(p.tenant!==who(player))return {ok:false,reason:"not_tenant"};if(Date.now()<Number(p.nextRentAt??0))return {ok:false,reason:"not_due",property:p};if(!Economy.withdraw(player,p.rent,{type:"rent_payment",propertyId:p.id}))return {ok:false,reason:"insufficient_funds",property:p};Treasury.collect(p.rent,{type:"rent_payment",propertyId:p.id});p.nextRentAt=Date.now()+p.rentInterval*1000;a[i]=p;save(a);emit("rentPaid",{player,property:p,amount:p.rent});return {ok:true,property:p,amount:p.rent};}
export function checkout(player,id){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i];if(p.tenant!==who(player))return {ok:false,reason:"not_tenant"};p.tenant=undefined;p.rentedAt=undefined;p.nextRentAt=undefined;a[i]=p;save(a);emit("propertyCheckout",{player,property:p});return {ok:true,property:p};}
export function status(player){return {owned:ownedBy(player),rented:rentedBy(player)};}

// Public Real Estate Platform API
export const registerProperty=upsert;
export function registerHotel(def){return upsert({...def,type:"hotel"});}
export const unregisterProperty=remove;
export function getOwner(id){return get(id)?.owner??null;}
export function canPurchase(player,id){const p=get(id);if(!p)return {ok:false,reason:"unknown_property"};if(p.type==="hotel")return {ok:false,reason:"not_for_sale"};if(p.owner||p.tenant)return {ok:false,reason:"unavailable"};if(!Economy.canAfford(player,p.price))return {ok:false,reason:"insufficient_funds"};return {ok:true,property:p};}
export function hasAccess(player,id){const p=get(id),n=who(player);if(!p||!n)return false;if(p.owner===n||p.tenant===n)return true;return Boolean(p.access?.[n]);}
export function grantAccess(owner,id,player,role="guest"){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i],o=who(owner),n=who(player);if(p.owner!==o||!n)return {ok:false,reason:"not_owner"};p.access={...(p.access??{}),[n]:String(role||"guest")};a[i]=p;save(a);emit("propertyAccessGranted",{owner,player,property:p,role:p.access[n]});return {ok:true,property:p};}
export function revokeAccess(owner,id,player){const a=load(),i=a.findIndex(x=>x.id===clean(id));if(i<0)return {ok:false,reason:"unknown_property"};const p=a[i],o=who(owner),n=who(player);if(p.owner!==o)return {ok:false,reason:"not_owner"};if(p.access)delete p.access[n];a[i]=p;save(a);emit("propertyAccessRevoked",{owner,player,property:p});return {ok:true,property:p};}
export function listAccess(id){const p=get(id);return p?Object.entries(p.access??{}).map(([player,role])=>({player,role})):[];}
export function listHotels(){return list({type:"hotel"});}
