import * as GameTest from "@minecraft/server-gametest";
import { world, system, GameMode, ItemStack } from "@minecraft/server";
import { operation } from "../api/gateway.js";
import * as Economy from "../core/economy.js";
import * as Jobs from "../core/jobs.js";
import * as Transactions from "../core/transactions.js";
import { setupWorld, grantMenuItem, countMenuItems } from "../core/setup.js";
const STRUCTURE="moneyz_tests:fixture",ALL="moneyz_internal";
const wait=(ticks=2)=>new Promise(r=>system.runTimeout(r,ticks));
const objective=n=>world.scoreboard.getObjective(n), money=()=>objective("Moneyz"), mailbox=()=>objective("MoneyzAPI");
function participantScore(obj,name){if(!obj)return undefined;try{const p=world.scoreboard.getParticipants().find(x=>x.displayName===name);return p===undefined?undefined:obj.getScore(p);}catch{return undefined;}}
function score(p){try{return money()?.getScore(p);}catch{return undefined;}}
function reg(name,fn,tag=ALL,max=400){
  return GameTest.register("moneyz_internal",name,test=>{
    let done=false, failure;
    try{test.killAllEntities();}catch{}
    Promise.resolve()
      .then(()=>fn(test))
      .then(()=>{done=true;})
      .catch(err=>{failure=err instanceof Error?err:new Error(String(err));done=true;});
    test.succeedWhen(()=>{
      if(failure) throw failure;
      test.assert(done,`Async test ${name} still running`);
    });
  }).structureName(STRUCTURE).maxTicks(max).batch(ALL).tag(ALL).tag(tag);
}
const players=new Map();
function sim(test,name){const p=test.spawnSimulatedPlayer({x:2,y:2,z:2},`MX_${name}`.slice(0,16),GameMode.creative);let n="";try{n=p.name;}catch{}if(n)players.set(n,p);test.runOnFinish(()=>{if(n)players.delete(n);try{test.removeSimulatedPlayer(p);}catch{}});return p;}
function cmd(c){return world.getDimension("overworld").runCommand(c);}function ok(t,c){let r;try{r=cmd(c);}catch(e){throw new Error(`Command failed: ${c}: ${e}`);}t.assert((r?.successCount??1)>0,`Command unsuccessful: ${c}`);}
async function readyPlayer(t,n){const p=sim(t,n);await wait(5);return p;}
async function api(t,body,timeout=50,sourcePlayer=undefined){
  let actor=sourcePlayer;
  if(!actor && typeof body?.player==="string") actor=players.get(body.player);
  // The internal suite passes the actual SimulatedPlayer object directly to the
  // same production gateway dispatcher. No command, selector, ScriptEvent or mailbox.
  if(body?.op==="economy.transfer" && actor){
    const to=players.get(String(body.to??body.target??""));
    if(!to)return {ok:false,reason:"target_not_found"};
    const ok=Economy.transfer(actor,to,Number(body.amount),{type:"api_transfer",source:"gametest"});
    return {ok,balance:Economy.getBalance(actor),targetBalance:Economy.getBalance(to)};
  }
  try{return await operation(actor?{sourceEntity:actor}:{},body??{});}
  catch(e){throw new Error(`Moneyz operation ${body?.op??"?"} threw: ${e}`);}
}
async function setBal(t,p,n){const r=await api(t,{op:"economy.set",amount:n},50,p);t.assert(r.ok,`set balance failed`);await wait(1);}
function give(p,typeId,amount=1){const c=p.getComponent("minecraft:inventory")?.container;if(!c)throw new Error("Player inventory unavailable");c.addItem(new ItemStack(typeId,amount));}
// Treasury mode/reserves are world-global. GameTests in the same run can overlap, so
// serialize tests that mutate Treasury state to prevent one test changing another's mode/balance.
let treasuryTestTail=Promise.resolve();
async function withTreasuryTest(fn){
  const previous=treasuryTestTail; let release;
  treasuryTestTail=new Promise(r=>{release=r;});
  await previous;
  try{return await fn();}finally{
    try{const T=await import("../core/treasury.js");T.setMode("classic");}catch{}
    release();
  }
}
async function clearReserve(T,itemId){const row=T.listReserves().find(x=>x.itemId===itemId);if(row?.count)T.removeReserve(itemId,row.count,row.value??0,{reason:"gametest_reset"});}

// Transport + platform contract
reg("transport_ping",async t=>{const r=await api(t,{op:"ping"});t.assert(r.ok&&r.value===1,"Mailbox ping failed");},"moneyz_internal_transport");
reg("transport_unknown_operation",async t=>{const r=await api(t,{op:"does.not.exist"});t.assert(!r.ok,"Unknown operation must fail");},"moneyz_internal_transport");
reg("platform_capabilities",async t=>{const r=await api(t,{op:"capabilities"});t.assert(r.ok&&r.value>=30,"Expected broad Moneyz capability surface");},"moneyz_internal_contract");
reg("moneyz_objective",async t=>t.assert(!!money(),"Moneyz objective missing"),"moneyz_internal_contract");
reg("setup_idempotent",async t=>{const p=await readyPlayer(t,"SETUP");const a=setupWorld(p,{grantItems:false}),b=setupWorld(p,{grantItems:false});t.assert(a.ok&&b.ok&&!!money()&&p.hasTag("moneyzAdmin")&&score(p)===0,"Setup did not reproduce legacy initialization");},"moneyz_internal_setup");
reg("setup_grants_legacy_items",async t=>{const p=await readyPlayer(t,"SETITEM");const c=p.getComponent("minecraft:inventory")?.container;t.assert(!!c,"Setup test inventory unavailable");const r=setupWorld(p,{grantItems:true});await wait(3);let egg=0;for(let i=0;i<c.size;i++){const it=c.getItem(i);if(!it)continue;if(String(it.typeId).includes("spawn_egg"))egg+=it.amount;}t.assert(r.ok&&countMenuItems(p)===1&&egg>=1,"Setup did not grant exactly one Moneyz Menu and an NPC spawn egg");},"moneyz_internal_setup");
reg("setup_menu_no_duplicate",async t=>{const p=await readyPlayer(t,"SETDUP");setupWorld(p,{grantItems:true});await wait(2);setupWorld(p,{grantItems:true});await wait(2);t.assert(countMenuItems(p)===1,"Repeated setup duplicated the Moneyz Menu item");},"moneyz_internal_setup");
reg("menu_item_grant_idempotent",async t=>{const p=await readyPlayer(t,"MENUGIVE");const a=grantMenuItem(p),b=grantMenuItem(p);t.assert(a.ok&&a.granted&&b.ok&&!b.granted&&countMenuItems(p)===1,"Menu item grant is not idempotent");const c=p.getComponent("minecraft:inventory")?.container;let lore=[];for(let i=0;i<c.size;i++){const it=c.getItem(i);if(it?.typeId==="zvortex:moneyz_menu"){lore=it.getLore();break;}}t.assert(lore.some(x=>x.includes("Moneyz Economy menu")),"Moneyz Menu lore missing");},"moneyz_internal_setup");

// Economy + transactions
reg("economy_set_balance",async t=>{const p=await readyPlayer(t,"ESET");await setBal(t,p,123);t.assert(score(p)===123,"Set balance mismatch");},"moneyz_internal_economy");
reg("economy_deposit",async t=>{const p=await readyPlayer(t,"EDEP");await setBal(t,p,100);const r=await api(t,{op:"economy.deposit",amount:25},50,p);t.assert(r.ok&&score(p)===125,"Deposit mismatch");},"moneyz_internal_economy");
reg("economy_withdraw",async t=>{const p=await readyPlayer(t,"EWDR");await setBal(t,p,100);const r=await api(t,{op:"economy.withdraw",amount:25},50,p);t.assert(r.ok&&score(p)===75,"Withdraw mismatch");},"moneyz_internal_economy");
reg("economy_overdraw_atomic",async t=>{const p=await readyPlayer(t,"EOVR");await setBal(t,p,5);const r=await api(t,{op:"economy.withdraw",amount:6},50,p);t.assert(!r.ok&&score(p)===5,"Overdraw changed balance");},"moneyz_internal_economy");
reg("economy_negative_deposit_rejected",async t=>{const p=await readyPlayer(t,"ENEG");await setBal(t,p,20);const r=await api(t,{op:"economy.deposit",amount:-5},50,p);t.assert(!r.ok&&score(p)===20,"Negative deposit accepted");},"moneyz_internal_economy");
reg("economy_transfer",async t=>{const a=await readyPlayer(t,"ETFA"),b=await readyPlayer(t,"ETFB");await setBal(t,a,80);await setBal(t,b,10);const r=await api(t,{op:"economy.transfer",to:b.name,amount:30},50,a);t.assert(r.ok&&score(a)===50&&score(b)===40,"Transfer mismatch");},"moneyz_internal_economy");
reg("economy_self_transfer_rejected",async t=>{const p=await readyPlayer(t,"SELF");await setBal(t,p,50);const r=await api(t,{op:"economy.transfer",to:p.name,amount:10},50,p);t.assert(!r.ok&&score(p)===50,"Self transfer accepted");},"moneyz_internal_economy");
reg("transactions_recorded",async t=>{const p=await readyPlayer(t,"TX");await setBal(t,p,40);const r=await api(t,{op:"economy.deposit",amount:2},50,p);t.assert(r.ok,"Deposit failed while testing transaction recording");await wait(1);const rows=Transactions.recent(10,{player:p});const hasSet=rows.some(x=>x.type==="api_set"||x.type==="set");const hasDeposit=rows.some(x=>x.type==="api_deposit"||x.type==="deposit");t.assert(hasSet&&hasDeposit,"Transactions not recorded for test player");},"moneyz_internal_transactions");

// Virtual accounts
reg("account_create_and_balance",async t=>{const id=`gt:acct:${system.currentTick}`;let r=await api(t,{op:"accounts.create",id});t.assert(r.ok,"Account create failed");r=await api(t,{op:"accounts.deposit",id,amount:100});t.assert(r.ok&&r.value===100,"Account deposit failed");},"moneyz_internal_accounts");
reg("account_withdraw",async t=>{const id=`gt:wd:${system.currentTick}`;await api(t,{op:"accounts.create",id});await api(t,{op:"accounts.deposit",id,amount:50});const r=await api(t,{op:"accounts.withdraw",id,amount:20});t.assert(r.ok&&r.value===30,"Account withdraw failed");},"moneyz_internal_accounts");
reg("account_overdraw_rejected",async t=>{const id=`gt:ov:${system.currentTick}`;await api(t,{op:"accounts.create",id});await api(t,{op:"accounts.deposit",id,amount:5});const r=await api(t,{op:"accounts.withdraw",id,amount:6});t.assert(!r.ok,"Account overdraw accepted");},"moneyz_internal_accounts");

// Jobs + legacy compatibility
reg("job_farmer_pay_contract",async t=>{const r=await api(t,{op:"jobs.get",id:"farmer"});t.assert(r.ok&&r.value===1000,"Farmer pay must be 1000");},"moneyz_internal_jobs");
reg("job_banker_pay_contract",async t=>{const r=await api(t,{op:"jobs.get",id:"banker"});t.assert(r.ok&&r.value===4000,"Banker pay must be 4000");},"moneyz_internal_jobs");
reg("job_requires_application",async t=>{const p=await readyPlayer(t,"JREQ");const r=await api(t,{op:"jobs.join",job:"farmer"},50,p);t.assert(!r.ok,"Job joined without application");},"moneyz_internal_jobs");
reg("job_application_tag",async t=>{const p=await readyPlayer(t,"JAPP");const r=await api(t,{op:"jobs.apply",player:p.name});await wait(1);t.assert(r.ok&&p.hasTag("apply"),"Application legacy tag missing");},"moneyz_internal_jobs");
reg("job_join_legacy_tag",async t=>{const p=await readyPlayer(t,"JJOIN");await api(t,{op:"jobs.apply",player:p.name});const r=await api(t,{op:"jobs.join",job:"farmer"},50,p);await wait(1);t.assert(r.ok&&p.hasTag("farmer")&&!p.hasTag("apply"),"Job compatibility tags wrong");},"moneyz_internal_jobs");
reg("job_current",async t=>{const p=await readyPlayer(t,"JCUR");await api(t,{op:"jobs.apply",player:p.name});await api(t,{op:"jobs.join",job:"farmer"},50,p);const r=await api(t,{op:"jobs.current",player:p.name});t.assert(r.ok&&r.value===1000,"Current job contract wrong");},"moneyz_internal_jobs");
reg("job_leave",async t=>{const p=await readyPlayer(t,"JLEAVE");await api(t,{op:"jobs.apply",player:p.name});await api(t,{op:"jobs.join",job:"farmer"},50,p);const r=await api(t,{op:"jobs.leave",player:p.name});await wait(1);t.assert(r.ok&&!p.hasTag("farmer"),"Job leave failed");},"moneyz_internal_jobs");
reg("legacy_job_migration_idempotent",async t=>{const p=await readyPlayer(t,"JMIG");p.addTag("farmer");Jobs.migrateLegacy(p);Jobs.migrateLegacy(p);t.assert(Jobs.current(p)?.id==="farmer"&&p.hasTag("farmer"),"Legacy job migration not idempotent");},"moneyz_internal_migration");

// Entitlements
reg("entitlement_roundtrip",async t=>{const p=await readyPlayer(t,"ENT");let r=await api(t,{op:"entitlements.grant",id:"gt:permit",legacyTag:"gtpermit"},50,p);t.assert(r.ok&&p.hasTag("gtpermit"),"Grant/tag failed");r=await api(t,{op:"entitlements.has",id:"gt:permit"},50,p);t.assert(r.ok&&r.value===1,"Has failed");r=await api(t,{op:"entitlements.revoke",id:"gt:permit"},50,p);await wait(1);t.assert(r.ok&&!p.hasTag("gtpermit"),"Revoke failed");},"moneyz_internal_entitlements");
reg("entitlement_missing",async t=>{const p=await readyPlayer(t,"ENT0");const r=await api(t,{op:"entitlements.has",id:"gt:none"},50,p);t.assert(r.ok&&r.value===0,"Missing entitlement reported present");},"moneyz_internal_entitlements");

// Shops + commerce
async function makeShop(t,id,stock={mode:"unlimited"}){await api(t,{op:"shops.delete",id});let r=await api(t,{op:"shops.create",id,name:"GT Shop"});t.assert(r.ok,"Shop create failed");r=await api(t,{op:"shops.addlisting",shop:id,typeId:"minecraft:apple",listingId:"apple",buyPrice:10,sellPrice:5,amount:1,stock});t.assert(r.ok,"Listing create failed");}
reg("shop_crud",async t=>{const id=`gt_shop_${system.currentTick}`;await makeShop(t,id);let r=await api(t,{op:"shops.exists",id});t.assert(r.ok&&r.value===1,"Shop missing");r=await api(t,{op:"shops.delete",id});t.assert(r.ok,"Delete failed");r=await api(t,{op:"shops.exists",id});t.assert(r.ok&&r.value===0,"Shop still exists");},"moneyz_internal_shops");
reg("shop_buy",async t=>{const p=await readyPlayer(t,"SBUY"),id=`gt_buy_${system.currentTick}`;await makeShop(t,id);await setBal(t,p,50);const r=await api(t,{op:"commerce.buy",shop:id,listing:"apple",quantity:2},50,p);t.assert(r.ok&&score(p)===30,"Shop buy failed");},"moneyz_internal_shops");
reg("shop_buy_insufficient_funds",async t=>{const p=await readyPlayer(t,"SNOM"),id=`gt_nom_${system.currentTick}`;await makeShop(t,id);await setBal(t,p,5);const r=await api(t,{op:"commerce.buy",shop:id,listing:"apple"},50,p);t.assert(!r.ok&&score(p)===5,"Insufficient-funds buy mutated balance");},"moneyz_internal_shops");
reg("shop_tracked_stock",async t=>{const p=await readyPlayer(t,"SSTK"),id=`gt_stk_${system.currentTick}`;await makeShop(t,id,{mode:"tracked",quantity:2});await setBal(t,p,50);let r=await api(t,{op:"commerce.buy",shop:id,listing:"apple"},50,p);t.assert(r.ok,"Tracked buy failed");r=await api(t,{op:"shops.stock",shop:id,listing:"apple"});t.assert(r.ok&&r.value===1,"Stock did not decrement");},"moneyz_internal_shops");
reg("shop_out_of_stock",async t=>{const p=await readyPlayer(t,"SOUT"),id=`gt_out_${system.currentTick}`;await makeShop(t,id,{mode:"tracked",quantity:0});await setBal(t,p,50);const r=await api(t,{op:"commerce.buy",shop:id,listing:"apple"},50,p);t.assert(!r.ok&&score(p)===50,"Out-of-stock purchase charged player");},"moneyz_internal_shops");
reg("shop_sell",async t=>{const p=await readyPlayer(t,"SSELL"),id=`gt_sell_${system.currentTick}`;await makeShop(t,id);await setBal(t,p,0);give(p,"minecraft:apple",2);await wait(1);const r=await api(t,{op:"commerce.sell",shop:id,listing:"apple",quantity:2},50,p);t.assert(r.ok&&score(p)===10,"Shop sell failed");},"moneyz_internal_shops");

// Products
reg("product_item_purchase",async t=>{const p=await readyPlayer(t,"PITEM"),id=`gt:item:${system.currentTick}`;await api(t,{op:"products.upsert",product:{id,name:"GT Apple",type:"item",price:12,itemId:"minecraft:apple",amount:1}});await setBal(t,p,20);const r=await api(t,{op:"products.purchase",id},50,p);t.assert(r.ok&&score(p)===8,"Item product purchase failed");},"moneyz_internal_products");
reg("product_entitlement_purchase",async t=>{const p=await readyPlayer(t,"PENT"),id=`gt:ent:${system.currentTick}`;await api(t,{op:"products.upsert",product:{id,name:"Permit",type:"entitlement",price:10,entitlementId:"gt:bought_permit",legacyTag:"boughtpermit"}});await setBal(t,p,20);const r=await api(t,{op:"products.purchase",id},50,p);t.assert(r.ok&&score(p)===10&&p.hasTag("boughtpermit"),"Entitlement product failed");},"moneyz_internal_products");
reg("product_unknown_no_charge",async t=>{const p=await readyPlayer(t,"PUNK");await setBal(t,p,20);const r=await api(t,{op:"products.purchase",id:"gt:no_such"},50,p);t.assert(!r.ok&&score(p)===20,"Unknown product charged player");},"moneyz_internal_products");
reg("product_delivery_failure_refund",async t=>{const p=await readyPlayer(t,"PFAIL"),id=`gt:bad:${system.currentTick}`;await api(t,{op:"products.upsert",product:{id,name:"Bad",type:"does_not_exist",price:10}});await setBal(t,p,20);const r=await api(t,{op:"products.purchase",id},50,p);t.assert(!r.ok&&score(p)===20,"Failed product did not refund");},"moneyz_internal_products");

// Properties + residential
reg("property_fresh_repository_not_required",async t=>{const p=await readyPlayer(t,"PSTAT");const r=await api(t,{op:"properties.status",player:p.name});t.assert(r.ok&&r.value>=0,"Property status failed");},"moneyz_internal_properties");
reg("property_buy_sell",async t=>{const p=await readyPlayer(t,"PROP"),id=`gt_prop_${system.currentTick}`;await api(t,{op:"properties.upsert",property:{id,name:"GT House",type:"residential",price:100,rent:10}});await setBal(t,p,150);let r=await api(t,{op:"properties.buy",id},50,p);t.assert(r.ok&&score(p)===50,"Property buy failed");r=await api(t,{op:"properties.status",player:p.name});t.assert(r.ok&&r.value>=1,"Ownership not recorded");r=await api(t,{op:"properties.sell",id,rate:1},50,p);t.assert(r.ok&&score(p)===150,"Property sell failed");},"moneyz_internal_properties");
reg("property_rent_checkout",async t=>{const p=await readyPlayer(t,"RENT"),id=`gt_rent_${system.currentTick}`;await api(t,{op:"properties.upsert",property:{id,name:"GT Rental",type:"residential",price:0,rent:15,rentInterval:60}});await setBal(t,p,50);let r=await api(t,{op:"properties.rent",id},50,p);t.assert(r.ok&&score(p)===35,"Rent failed");r=await api(t,{op:"properties.checkout",id},50,p);t.assert(r.ok,"Checkout failed");},"moneyz_internal_properties");
reg("property_double_occupancy_rejected",async t=>{const a=await readyPlayer(t,"R1"),b=await readyPlayer(t,"R2"),id=`gt_occ_${system.currentTick}`;await api(t,{op:"properties.upsert",property:{id,name:"GT Occupied",type:"residential",price:0,rent:5}});await setBal(t,a,20);await setBal(t,b,20);t.assert((await api(t,{op:"properties.rent",id},50,a)).ok,"First rent failed");const r=await api(t,{op:"properties.rent",player:b.name,id});t.assert(!r.ok&&score(b)===20,"Second tenant accepted/charged");},"moneyz_internal_properties");

// Hotels + reservations
reg("hotel_booking",async t=>{const p=await readyPlayer(t,"HOTEL"),id=`gt_hotel_${system.currentTick}`;await api(t,{op:"properties.upsert",property:{id,name:"GT Room",type:"hotel",rent:25,rentInterval:60}});await setBal(t,p,100);let r=await api(t,{op:"reservations.book",propertyId:id,nights:2,durationMs:60000},50,p);t.assert(r.ok&&score(p)===50,"Hotel booking failed");r=await api(t,{op:"reservations.active",player:p.name});t.assert(r.ok&&r.value===1,"Active reservation missing");},"moneyz_internal_reservations");
reg("hotel_double_booking_rejected",async t=>{const a=await readyPlayer(t,"H1"),b=await readyPlayer(t,"H2"),id=`gt_room_${system.currentTick}`;await api(t,{op:"properties.upsert",property:{id,name:"GT Room",type:"hotel",rent:10,rentInterval:60}});await setBal(t,a,50);await setBal(t,b,50);t.assert((await api(t,{op:"reservations.book",propertyId:id,nights:1,durationMs:60000},50,a)).ok,"First booking failed");const r=await api(t,{op:"reservations.book",player:b.name,propertyId:id,nights:1,durationMs:60000});t.assert(!r.ok&&score(b)===50,"Double booking accepted/charged");},"moneyz_internal_reservations");

// Exchanges / recovered 1.10.1 defaults
for(const [id,value] of [["coal",5],["copper",10],["iron",50],["gold",25],["emerald",100],["diamond",75],["netherite",1000]])reg(`exchange_default_${id}`,async t=>{const r=await api(t,{op:"exchanges.get",id});t.assert(r.ok&&r.value===value,`${id} exchange expected ${value}`);},"moneyz_internal_exchanges");
reg("exchange_buy",async t=>{const p=await readyPlayer(t,"XBUY");await setBal(t,p,20);const r=await api(t,{op:"exchanges.execute",id:"coal",direction:"buy",bundles:2},50,p);t.assert(r.ok&&score(p)===10,"Exchange buy failed");},"moneyz_internal_exchanges");
reg("exchange_sell",async t=>{const p=await readyPlayer(t,"XSELL");await setBal(t,p,0);give(p,"minecraft:coal",2);await wait(1);const r=await api(t,{op:"exchanges.execute",id:"coal",direction:"sell",bundles:2},50,p);t.assert(r.ok&&score(p)===10,"Exchange sell failed");},"moneyz_internal_exchanges");
reg("exchange_insufficient_funds",async t=>{const p=await readyPlayer(t,"XNO");await setBal(t,p,4);const r=await api(t,{op:"exchanges.execute",id:"coal",direction:"buy"},50,p);t.assert(!r.ok&&score(p)===4,"Exchange overdrew player");},"moneyz_internal_exchanges");

// Quests
reg("quests_available",async t=>{const p=await readyPlayer(t,"QAVL");const r=await api(t,{op:"quests.available",player:p.name});t.assert(r.ok&&r.value>0,"No quests available");},"moneyz_internal_quests");
reg("quest_start_abandon",async t=>{const p=await readyPlayer(t,"QSTA");let r=await api(t,{op:"quests.start",id:"mine_10"},50,p);t.assert(r.ok,"Quest start failed");r=await api(t,{op:"quests.active",player:p.name});t.assert(r.ok&&r.value===1,"Quest not active");r=await api(t,{op:"quests.abandon",player:p.name});t.assert(r.ok,"Quest abandon failed");},"moneyz_internal_quests");
reg("quest_unknown_rejected",async t=>{const p=await readyPlayer(t,"QUNK");const r=await api(t,{op:"quests.start",id:"no_such_quest"},50,p);t.assert(!r.ok,"Unknown quest accepted");},"moneyz_internal_quests");
reg("quest_balance_requirement",async t=>{const p=await readyPlayer(t,"QBAL");await setBal(t,p,999);const r=await api(t,{op:"quests.start",id:"maintain_1000_5m"},50,p);t.assert(!r.ok,"Balance quest started below threshold");},"moneyz_internal_quests");

// Services / UI routing existence (UI itself remains manual smoke test)
for(const id of ["moneyz:menu","moneyz:atm","moneyz:send","moneyz:help","moneyz:quests","moneyz:jobs","moneyz:realtor","moneyz:hotel","moneyz:pets","moneyz:products","moneyz:admin"])reg(`service_${id.replace(/[^a-z0-9]/gi,"_")}`,async t=>{const r=await api(t,{op:"services.exists",id});t.assert(r.ok&&r.value===1,`Missing service ${id}`);},"moneyz_internal_services");
reg("services_registry_nonempty",async t=>{const r=await api(t,{op:"services.list"});t.assert(r.ok&&r.value>=10,"Service registry unexpectedly small");},"moneyz_internal_services");

// Failure contract
reg("missing_player_rejected",async t=>{const r=await api(t,{op:"economy.deposit",player:"__NO_SUCH_PLAYER__",amount:10});t.assert(!r.ok,"Missing player accepted");},"moneyz_internal_security");
reg("unknown_job_rejected",async t=>{const p=await readyPlayer(t,"JBAD");await api(t,{op:"jobs.apply",player:p.name});const r=await api(t,{op:"jobs.join",job:"no_such_job"},50,p);t.assert(!r.ok,"Unknown job accepted");},"moneyz_internal_security");

// Stress transport + economy; intentionally separate from full suite for soak runs.
for(let i=0;i<20;i++)reg(`stress_gateway_${i}`,async t=>{const p=await readyPlayer(t,`S${i}`),base=1000+i;await setBal(t,p,base);let r=await api(t,{op:"economy.deposit",amount:7},50,p);t.assert(r.ok,"Stress deposit failed");r=await api(t,{op:"economy.withdraw",amount:3},50,p);t.assert(r.ok&&score(p)===base+4,"Stress roundtrip mismatch");},"moneyz_internal_stress");

// Treasury / reserve economy
reg("treasury_liquidity_guard",async t=>withTreasuryTest(async()=>{const Treasury=await import("../core/treasury.js");Treasury.setMode("treasury");Treasury.setBalance(5);const r=Treasury.payout(10,{type:"gametest"});t.assert(!r.ok&&r.reason==="treasury_insufficient_funds"&&Treasury.getBalance()===5,"Treasury allowed an insolvent payout");Treasury.setMode("classic");}),"moneyz_internal_treasury");
reg("treasury_collect_and_payout",async t=>withTreasuryTest(async()=>{const Treasury=await import("../core/treasury.js");Treasury.setMode("treasury");Treasury.setBalance(100);Treasury.collect(25,{type:"gametest"});const r=Treasury.payout(40,{type:"gametest"});t.assert(r.ok&&Treasury.getBalance()===85,"Treasury accounting mismatch");Treasury.setMode("classic");}),"moneyz_internal_treasury");
reg("reserve_assets",async t=>withTreasuryTest(async()=>{const Treasury=await import("../core/treasury.js");Treasury.setMode("reserve");await clearReserve(Treasury,"minecraft:diamond");Treasury.setBalance(0);Treasury.addReserve("minecraft:diamond",2,150);t.assert(Treasury.reserveCount("minecraft:diamond")>=2&&Treasury.getBalance()===150,"Resource deposit did not back reserve economy");const r=Treasury.removeReserve("minecraft:diamond",1,75);t.assert(r.ok,"Reserve withdrawal failed");Treasury.setMode("classic");}),"moneyz_internal_treasury");
reg("treasury_admin_reserve_set",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js"),id="gt:admin_reserve";T.clearReserve(id);T.setReserve(id,12,360,{reason:"gametest_admin_set"});let r=T.listReserves().find(x=>x.itemId===id);t.assert(r?.count===12&&r?.value===360,"Admin exact reserve set failed");T.setReserve(id,5,125,{reason:"gametest_admin_edit"});r=T.listReserves().find(x=>x.itemId===id);t.assert(r?.count===5&&r?.value===125,"Admin reserve edit failed");T.clearReserve(id);t.assert(!T.listReserves().some(x=>x.itemId===id),"Admin reserve clear failed");}),"moneyz_internal_treasury");
reg("treasury_mode_values",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js");for(const mode of ["classic","treasury","reserve"]){T.setMode(mode);t.assert(T.getMode()===mode,`Treasury mode ${mode} did not persist`);}T.setMode("classic");}),"moneyz_internal_treasury");

// Public Real Estate API
reg("realestate_provider_registration",async t=>{const P=await import("../core/properties.js"),id=`gt_provider_${system.currentTick}`;const p=P.registerProperty({id,provider:"gametest",name:"Provider House",price:123,metadata:{district:"test"}});t.assert(p.provider==="gametest"&&P.get(id)?.metadata?.district==="test","Provider property registration failed");P.remove(id);},"moneyz_internal_realestate_api");
reg("realestate_access_control",async t=>{const P=await import("../core/properties.js"),owner=await readyPlayer(t,"REOWN"),guest=await readyPlayer(t,"REGST"),id=`gt_access_${system.currentTick}`;P.registerProperty({id,name:"Access House",price:1});await setBal(t,owner,5);const b=P.buy(owner,id);t.assert(b.ok,"Owner could not buy access-test property");t.assert(P.grantAccess(owner,id,guest,"guest").ok&&P.hasAccess(guest,id),"Guest access grant failed");t.assert(P.revokeAccess(owner,id,guest).ok&&!P.hasAccess(guest,id),"Guest access revoke failed");P.remove(id);},"moneyz_internal_realestate_api");
reg("hotel_provider_api",async t=>{const P=await import("../core/properties.js"),R=await import("../core/reservations.js"),id=`gt_provider_hotel_${system.currentTick}`;P.registerHotel({id,provider:"gametest",name:"Provider Room",rent:10,rentInterval:60});t.assert(P.get(id)?.type==="hotel"&&R.isAvailable(id),"Hotel provider registration/availability failed");P.remove(id);},"moneyz_internal_realestate_api");


// 2.0 public discovery / observability API
reg("api_metrics_snapshot",async t=>{const r=await api(t,{op:"metrics.snapshot"});t.assert(r.ok&&Number.isFinite(r.metrics?.onlinePlayers)&&Number.isFinite(r.metrics?.playerMoney),"Metrics snapshot API failed");},"moneyz_internal_public_api");
reg("api_audit_query",async t=>{const A=await import("../core/audit.js");A.record("gametest.public_api",{actor:"gametest",subject:"api"});const r=await api(t,{op:"audit.query",action:"gametest.public_api",limit:10});t.assert(r.ok&&r.entries?.some(x=>x.action==="gametest.public_api"),"Audit query API failed");},"moneyz_internal_public_api");
reg("api_config_read",async t=>{const r=await api(t,{op:"config.get",key:"dailyReward"});t.assert(r.ok&&r.key==="dailyReward"&&r.value!==undefined,"Config read API failed");const all=await api(t,{op:"config.list"});t.assert(all.ok&&all.config?.dailyReward!==undefined,"Config list API failed");},"moneyz_internal_public_api");
reg("api_permissions_discovery",async t=>{const r=await api(t,{op:"permissions.list"});t.assert(r.ok&&Array.isArray(r.permissions),"Permission discovery API failed");},"moneyz_internal_public_api");
reg("api_pricing_calculate",async t=>{const r=await api(t,{op:"pricing.calculate",base:123,context:{source:"gametest"}});t.assert(r.ok&&r.value===123,"Pricing calculate API failed");},"moneyz_internal_public_api");
reg("api_fees_calculate",async t=>{const r=await api(t,{op:"fees.calculate",context:{amount:100,source:"gametest"}});t.assert(r.ok&&Array.isArray(r.fees)&&Number.isFinite(r.value),"Fee calculate API failed");},"moneyz_internal_public_api");
reg("api_extension_discovery",async t=>{const r=await api(t,{op:"extensions.list"});t.assert(r.ok&&Array.isArray(r.extensions),"Extension discovery API failed");const c=await api(t,{op:"currencies.list"});t.assert(c.ok&&Array.isArray(c.currencies),"Currency discovery API failed");},"moneyz_internal_public_api");

// Treasury integration / conservation tests
reg("treasury_shop_purchase_inflow",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js"),S=await import("../repositories/shops.js");const p=await readyPlayer(t,"TSBUY"),id=`gt_tsbuy_${system.currentTick}`;T.setMode("treasury");T.setBalance(0);S.createShop({id,name:"Treasury Shop"});S.addListing(id,{typeId:"minecraft:stone",listingId:"stone",buy:{price:10,amount:1},sell:{price:-1,amount:1},stock:{mode:"unlimited"}});await setBal(t,p,100);const beforePlayer=score(p),beforeTreasury=T.getBalance(),r=await api(t,{op:"commerce.buy",shop:id,listing:"stone"},50,p);const charged=Number(r.total);t.assert(r.ok&&Number.isFinite(charged)&&charged>0&&score(p)===beforePlayer-charged&&T.getBalance()===beforeTreasury+charged,`Shop purchase treasury mismatch: ok=${r.ok} total=${r.total} player=${score(p)}/${beforePlayer} treasury=${T.getBalance()}/${beforeTreasury}`);S.deleteShop(id);T.setMode("classic");}),"moneyz_internal_treasury_integration");
reg("treasury_shop_sale_insolvency_atomic",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js"),S=await import("../repositories/shops.js"),I=await import("../services/inventory.js");const p=await readyPlayer(t,"TSSELL"),id=`gt_tssell_${system.currentTick}`;T.setMode("treasury");T.setBalance(4);S.createShop({id,name:"Treasury Sell"});S.addListing(id,{typeId:"minecraft:coal",listingId:"coal",buy:{price:-1,amount:1},sell:{price:10,amount:1},stock:{mode:"unlimited"}});give(p,"minecraft:coal",1);await setBal(t,p,0);const before=I.count(p,"minecraft:coal"),r=await api(t,{op:"commerce.sell",shop:id,listing:"coal"},50,p);t.assert(!r.ok&&r.reason==="treasury_insufficient_funds"&&score(p)===0&&I.count(p,"minecraft:coal")===before&&T.getBalance()===4,"Insolvent shop sale was not atomic");S.deleteShop(id);T.setMode("classic");}),"moneyz_internal_treasury_integration");
reg("treasury_property_sale_insolvency_keeps_owner",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js"),P=await import("../core/properties.js");const p=await readyPlayer(t,"TPSALE"),id=`gt_tpsale_${system.currentTick}`;T.setMode("treasury");T.setBalance(0);P.registerProperty({id,name:"Treasury House",price:100});await setBal(t,p,100);t.assert(P.buy(p,id).ok,"Treasury property purchase failed");T.setBalance(10);const r=P.sell(p,id,{rate:1});t.assert(!r.ok&&P.getOwner(id)===p.name&&score(p)===0&&T.getBalance()===10,"Insolvent property sale changed ownership/balance");P.remove(id);T.setMode("classic");}),"moneyz_internal_treasury_integration");
reg("treasury_hotel_booking_inflow",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js"),P=await import("../core/properties.js"),R=await import("../core/reservations.js");const p=await readyPlayer(t,"THOTEL"),id=`gt_thotel_${system.currentTick}`;T.setMode("treasury");T.setBalance(0);P.registerHotel({id,name:"Treasury Room",rent:15,rentInterval:60});await setBal(t,p,50);const r=R.book(p,id,{nights:2,durationMs:60000});t.assert(r.ok&&score(p)===20&&T.getBalance()===30,"Hotel booking did not fund treasury");P.remove(id);T.setMode("classic");}),"moneyz_internal_treasury_integration");
reg("reserve_exchange_requires_inventory",async t=>withTreasuryTest(async()=>{const T=await import("../core/treasury.js");const p=await readyPlayer(t,"RXINV");T.setMode("reserve");await clearReserve(T,"minecraft:diamond");T.setBalance(100);await setBal(t,p,100);const before=score(p),r=await api(t,{op:"exchanges.execute",id:"diamond",direction:"buy",bundles:1},50,p);t.assert(!r.ok&&r.reason==="reserve_insufficient_items"&&score(p)===before,"Reserve exchange created an unbacked resource");T.setMode("classic");}),"moneyz_internal_treasury_integration");

// Real Estate provider/API integration tests
reg("realestate_gateway_registration_roundtrip",async t=>{const id=`gt:gateway_house_${system.currentTick}`;let r=await api(t,{op:"realestate.register",property:{id,provider:"gametest",name:"Gateway House",type:"residential",price:77,metadata:{district:"api"}}});t.assert(r.ok&&r.property?.provider==="gametest","Gateway property registration failed");r=await api(t,{op:"realestate.get",id});t.assert(r.ok&&r.property?.metadata?.district==="api","Gateway property roundtrip lost metadata");await api(t,{op:"realestate.unregister",id});},"moneyz_internal_realestate_api");
reg("realestate_ownedby_gateway",async t=>{const P=await import("../core/properties.js"),p=await readyPlayer(t,"REOWNBY"),id=`gt_ownedby_${system.currentTick}`;P.registerProperty({id,name:"OwnedBy House",price:5});await setBal(t,p,10);t.assert(P.buy(p,id).ok,"OwnedBy setup purchase failed");const r=await api(t,{op:"realestate.ownedby"},50,p);t.assert(r.ok&&r.properties?.some(x=>x.id===id),"realestate.ownedBy gateway omitted owned property");P.remove(id);},"moneyz_internal_realestate_api");
reg("realestate_nonowner_cannot_grant_access",async t=>{const P=await import("../core/properties.js"),owner=await readyPlayer(t,"RACOWN"),other=await readyPlayer(t,"RACOTH"),guest=await readyPlayer(t,"RACGST"),id=`gt_accessdeny_${system.currentTick}`;P.registerProperty({id,name:"Private House",price:1});await setBal(t,owner,2);t.assert(P.buy(owner,id).ok,"Access setup purchase failed");const r=P.grantAccess(other,id,guest,"guest");t.assert(!r.ok&&!P.hasAccess(guest,id),"Non-owner granted property access");P.remove(id);},"moneyz_internal_realestate_api");
reg("realestate_hotel_reservation_gateway",async t=>{const id=`gt:api_hotel_${system.currentTick}`;let r=await api(t,{op:"hotels.register",property:{id,provider:"gametest",name:"API Hotel",rent:8,rentInterval:60}});t.assert(r.ok,"Hotel gateway registration failed");r=await api(t,{op:"reservations.available",propertyId:id});t.assert(r.ok&&r.available,"New provider hotel not available");await api(t,{op:"realestate.unregister",id});},"moneyz_internal_realestate_api");


// Lucky Purchase — shop-driven catalog / live stock
reg("lucky_eligible_from_shop_catalog",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),id=`gt_lucky_cat_${system.currentTick}`;S.createShop({id,name:"Lucky Catalog"});S.addListing(id,{typeId:"minecraft:apple",listingId:"apple",category:"food",buy:{price:25,amount:2},sell:{price:-1,amount:1},stock:{mode:"tracked",quantity:3}});const rows=L.eligibleProducts({shops:[id],useStock:true});t.assert(rows.length===1&&rows[0].value===25&&rows[0].amount===2&&rows[0].stock===3,"Lucky did not resolve current Shop listing data");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_out_of_stock_excluded",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),id=`gt_lucky_oos_${system.currentTick}`;S.createShop({id,name:"Lucky OOS"});S.addListing(id,{typeId:"minecraft:apple",listingId:"apple",buy:{price:10,amount:1},sell:{price:-1,amount:1},stock:{mode:"tracked",quantity:0}});t.assert(L.eligibleProducts({shops:[id],useStock:true}).length===0,"Out-of-stock listing remained Lucky eligible");S.adjustStock(id,"apple",1);t.assert(L.eligibleProducts({shops:[id],useStock:true}).length===1,"Restocked listing did not become Lucky eligible");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_unlimited_stock_eligible",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),id=`gt_lucky_inf_${system.currentTick}`;S.createShop({id,name:"Lucky Unlimited"});S.addListing(id,{typeId:"minecraft:stone",listingId:"stone",buy:{price:8,amount:4},sell:{price:-1,amount:1},stock:{mode:"unlimited"}});const rows=L.eligibleProducts({shops:[id],useStock:true});t.assert(rows.length===1&&rows[0].stock===-1,"Unlimited-stock listing was excluded");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_purchase_decrements_shared_stock",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),I=await import("../services/inventory.js"),p=await readyPlayer(t,"LSTOCK"),id=`gt_lucky_buy_${system.currentTick}`;S.createShop({id,name:"Lucky Stock"});S.addListing(id,{typeId:"minecraft:apple",listingId:"apple",buy:{price:40,amount:2},sell:{price:-1,amount:1},stock:{mode:"tracked",quantity:2}});await setBal(t,p,100);const before=I.count(p,"minecraft:apple"),r=await L.purchase(p,{price:15,shops:[id],useStock:true});t.assert(r.ok&&score(p)===85&&S.getListing(id,"apple").stock.quantity===1&&I.count(p,"minecraft:apple")===before+2,"Lucky purchase did not use shared Shop stock/delivery");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_stock_restore_on_delivery_failure",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),p=await readyPlayer(t,"LROLL"),id=`gt_lucky_roll_${system.currentTick}`;S.createShop({id,name:"Lucky Rollback"});S.addListing(id,{typeId:"minecraft:apple",listingId:"apple",buy:{price:10,amount:1},sell:{price:-1,amount:1},stock:{mode:"tracked",quantity:1}});S.updateListing(id,"apple",{productId:"gt:missing_product"});await setBal(t,p,50);const r=await L.purchase(p,{price:15,shops:[id],useStock:true});t.assert(!r.ok&&score(p)===50&&S.getListing(id,"apple").stock.quantity===1,"Lucky failure did not refund Moneyz and restore stock");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_disabled_listing_excluded",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),id=`gt_lucky_dis_${system.currentTick}`;S.createShop({id,name:"Lucky Disabled"});S.addListing(id,{typeId:"minecraft:apple",listingId:"apple",buy:{price:10,amount:1},sell:{price:-1,amount:1},stock:{mode:"unlimited"}});S.updateListing(id,"apple",{lucky:{enabled:false}});t.assert(L.eligibleProducts({shops:[id]}).length===0,"Lucky-disabled listing remained eligible");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_category_filter",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),id=`gt_lucky_filter_${system.currentTick}`;S.createShop({id,name:"Lucky Filter"});S.addListing(id,{typeId:"minecraft:apple",listingId:"food",category:"food",buy:{price:10,amount:1},sell:{price:-1,amount:1},stock:{mode:"unlimited"}});S.addListing(id,{typeId:"minecraft:stone",listingId:"blocks",category:"blocks",buy:{price:10,amount:1},sell:{price:-1,amount:1},stock:{mode:"unlimited"}});const rows=L.eligibleProducts({shops:[id],categories:["food"]});t.assert(rows.length===1&&rows[0].listingId==="food","Lucky category filter failed");S.deleteShop(id);},"moneyz_internal_lucky");
reg("lucky_gateway_discovery",async t=>{const r=await api(t,{op:"lucky.config"});t.assert(r.ok&&Number.isFinite(r.config?.price)&&typeof r.config?.useStock==="boolean","Lucky public API config failed");const e=await api(t,{op:"lucky.eligible",options:{shops:["__no_such_shop__"]}});t.assert(e.ok&&Array.isArray(e.products)&&e.products.length===0,"Lucky eligible gateway failed");},"moneyz_internal_lucky");

// Runtime ItemStack templates / extension registries
reg("runtime_catalogs",async t=>{const I=await import("../core/item_templates.js");const items=I.itemCatalog("diamond",500),ench=I.enchantmentCatalog(),pot=I.potionCatalog();t.assert(items.some(x=>x.includes("diamond"))&&ench.length>0&&Array.isArray(pot.effects)&&Array.isArray(pot.deliveries),"Runtime item/enchantment/potion catalogs unavailable");},"moneyz_internal_runtime_items");
reg("item_template_capture_roundtrip",async t=>{const I=await import("../core/item_templates.js");const item=new ItemStack("minecraft:diamond_sword",1);item.nameTag="GT Blade";item.setLore(["Runtime template"]);const spec=I.capture(item),copy=I.create(spec);t.assert(spec.typeId==="minecraft:diamond_sword"&&copy.nameTag==="GT Blade"&&copy.getLore()?.[0]==="Runtime template","Item template capture/rebuild lost state");},"moneyz_internal_runtime_items");
reg("potion_template_roundtrip",async t=>{const I=await import("../core/item_templates.js"),p=I.potionCatalog();if(!p.effects.length||!p.deliveries.length)return;let stack=null;for(const e of p.effects){for(const d of p.deliveries){try{stack=I.create({typeId:"minecraft:potion",amount:1,potion:{effectId:e,deliveryId:d}});if(stack)break;}catch{}}if(stack)break;}t.assert(!!stack,"No runtime potion combination could be resolved");const spec=I.capture(stack),copy=I.create(spec);t.assert(spec.potion?.effectId&&copy.getComponent("minecraft:potion")?.potionEffectType?.id===spec.potion.effectId,"Potion template lost runtime potion state");},"moneyz_internal_runtime_items");
reg("shop_template_lucky_delivery",async t=>{const S=await import("../repositories/shops.js"),L=await import("../core/lucky.js"),I=await import("../core/item_templates.js"),p=await readyPlayer(t,"TMPLUCK"),id=`gt_tmplucky_${system.currentTick}`;const base=new ItemStack("minecraft:diamond_sword",1);base.nameTag="Lucky GT Blade";base.setLore(["Exact product"]);const spec=I.capture(base);S.createShop({id,name:"Template Lucky"});S.addListing(id,{typeId:base.typeId,listingId:"blade",itemTemplate:spec,buy:{price:20,amount:1},sell:{price:10,amount:1},stock:{mode:"tracked",quantity:1}});await setBal(t,p,100);const r=await L.purchase(p,{price:5,shops:[id],useStock:true});const c=p.getComponent("minecraft:inventory")?.container;let found=false;for(let n=0;n<(c?.size??0);n++){const it=c.getItem(n);if(it?.nameTag==="Lucky GT Blade"&&it.getLore()?.[0]==="Exact product")found=true;}t.assert(r.ok&&found&&S.getListing(id,"blade").stock.quantity===0,"Lucky Purchase did not preserve exact ItemStack template/shared stock");S.deleteShop(id);},"moneyz_internal_runtime_items");
reg("quest_extension_registry",async t=>{const Q=await import("../quest/engine.js"),type=`gt:objective_${system.currentTick}`,id=`gt:quest_${system.currentTick}`;const offType=Q.registerObjectiveType(type,{initialProgress:q=>({current:0,target:q.objective.count})});const offQuest=Q.registerQuest({id,property:`GTQuest${system.currentTick}`,description:"Extension Quest",objective:{type,count:2},reward:{type:"Moneyz",amount:1}});t.assert(Q.listObjectiveTypes().includes(type)&&Q.getDefinition(id)?.objective?.type===type,"Quest extension registration failed");offQuest();offType();},"moneyz_internal_extensions");
reg("game_extension_registry",async t=>{const G=await import("../core/games.js"),id=`gt:game_${system.currentTick}`;const off=G.register({id,name:"GT Extension Game",category:"chance",play:async()=>({ok:true,value:42})});t.assert(G.get(id)?.name==="GT Extension Game"&&G.list({category:"chance"}).some(x=>x.id===id),"Game extension discovery failed");const p=await readyPlayer(t,"EXTGAME"),r=await G.play(p,id,{source:"gametest"});t.assert(r.ok&&r.value===42,"Game extension play callback failed");off();t.assert(!G.get(id),"Game extension unregister failed");},"moneyz_internal_extensions");
reg("extension_gateway_discovery",async t=>{const c=await api(t,{op:"catalog.enchantments"}),q=await api(t,{op:"quests.objective_types"}),g=await api(t,{op:"games.list"});t.assert(c.ok&&Array.isArray(c.enchantments)&&q.ok&&Array.isArray(q.types)&&g.ok&&Array.isArray(g.games),"Runtime/extension gateway discovery failed");},"moneyz_internal_extensions");
reg("runtime_applicable_enchantment_selector",async t=>{const I=await import("../core/item_templates.js"),rows=I.applicableEnchantments({version:1,typeId:"minecraft:diamond_sword",amount:1});t.assert(rows.length>0&&rows.every(x=>x.id&&x.maxLevel>=1),"Runtime compatible enchantment selector returned no valid sword enchantments");},"moneyz_internal_runtime_items");
reg("runtime_potion_variant_selector",async t=>{const I=await import("../core/item_templates.js"),rows=I.potionVariants();t.assert(rows.length>0,"Runtime potion selector found no constructible variants");for(const row of rows.slice(0,20)){const stack=I.create({version:1,typeId:row.typeId,amount:1,potion:{effectId:row.effectId,deliveryId:row.deliveryId}});t.assert(stack.typeId===row.typeId,"Runtime potion variant reconstructed as wrong item type");}},"moneyz_internal_runtime_items");
reg("product_bundle_exact_template_delivery",async t=>{const P=await import("../core/products.js"),I=await import("../core/item_templates.js"),p=await readyPlayer(t,"BTMPL"),id=`gt:bundle_template:${system.currentTick}`,base=new ItemStack("minecraft:diamond_sword",1);base.nameTag="Bundle GT Blade";const spec=I.capture(base);P.upsert({id,name:"Exact Bundle",type:"bundle",price:1,contents:[{type:"item",itemId:spec.typeId,amount:1,itemTemplate:spec}]});await setBal(t,p,5);const r=await P.purchase(p,id,{source:"gametest"}),c=p.getComponent("minecraft:inventory")?.container;let found=false;for(let n=0;n<(c?.size??0);n++)if(c.getItem(n)?.nameTag==="Bundle GT Blade")found=true;t.assert(r.ok&&found,"Bundle product did not deliver exact ItemStack template");P.remove(id);},"moneyz_internal_runtime_items");
reg("tipped_arrow_selector_is_separate",async t=>{const I=await import("../core/item_templates.js"),arrows=I.tippedArrowVariants(),pots=I.potionVariants();t.assert(arrows.length>0&&arrows.every(x=>x.typeId==="minecraft:arrow"&&x.data>0),"Tipped-arrow selector returned invalid arrow variants");t.assert(pots.every(x=>x.typeId!=="minecraft:arrow"),"Potion selector unexpectedly returned an arrow delivery variant");},"moneyz_internal_runtime_items");
reg("tipped_arrow_template_validation",async t=>{const I=await import("../core/item_templates.js"),v=I.tippedArrowVariants()[0],spec={version:1,typeId:"minecraft:arrow",amount:4,tippedArrow:{data:v.data,name:v.name}};t.assert(I.validate(spec).ok&&I.describe(spec).includes("Arrow of"),"Tipped-arrow template did not validate/describe correctly");},"moneyz_internal_runtime_items");

reg("potion_variants_group_levels",async t=>{const I=await import("../core/item_templates.js"),rows=I.potionVariants(),families=I.potionFamilies();t.assert(rows.length>0&&families.length>0,"Potion variant grouping returned no runtime variants");for(const row of rows.slice(0,50)){const info=I.potionVariantInfo(row.effectId);t.assert(!!info.family&&!!info.variant,"Potion variant missing family/level metadata");const fam=I.potionFamilies(row.deliveryId).find(x=>x.family===info.family);t.assert(!!fam?.variants.some(x=>x.effectId===row.effectId),"Runtime potion variant missing from its effect/level selector");}},"moneyz_internal_runtime_items");
reg("tipped_arrow_levels_groupable",async t=>{const I=await import("../core/item_templates.js"),rows=I.tippedArrowVariants();t.assert(rows.some(x=>/ II/.test(x.name)),"Tipped-arrow catalog has no enhanced/II variants");t.assert(rows.some(x=>/\\([0-9]+:[0-9]+\\)/.test(x.name)),"Tipped-arrow catalog has no duration variants");},"moneyz_internal_runtime_items");
