import * as Economy from "../core/economy.js";
import * as Inventory from "./inventory.js";
import * as Pricing from "../core/pricing.js";
import * as Fees from "../core/fees.js";
import * as Accounts from "../core/accounts.js";
import * as Shops from "../repositories/shops.js";
import * as Products from "../core/products.js";

function listingProduct(listing,side){const d=listing?.[side];return {id:listing?.typeId,amount:d?.amount??1,price:d?.price??0,data:listing?.legacy?.[side==="buy"?"buyDamage":"sellDamage"]??0};}
function quote(side,player,shop,listing,quantity=1){const d=listing?.[side];if(!shop||!listing||listing.enabled===false||!d?.enabled)return {ok:false,reason:"disabled"};quantity=Math.max(1,Math.floor(Number(quantity)||1));const base=Math.max(0,Math.round(Number(d.price)||0))*quantity;const price=Pricing.calculate(base,{operation:side,player,shop,listing,quantity});const fees=Fees.calculate({operation:side,player,shop,listing,quantity,subtotal:price});const feeTotal=fees.reduce((n,f)=>n+f.amount,0);return {ok:true,quantity,subtotal:price,fees,feeTotal,total:side==="buy"?price+feeTotal:Math.max(0,price-feeTotal)};}
export const quoteBuy=(player,shopId,listingId,q=1)=>quote("buy",player,Shops.getShop(shopId),Shops.getListing(shopId,listingId),q);
export const quoteSell=(player,shopId,listingId,q=1)=>quote("sell",player,Shops.getShop(shopId),Shops.getListing(shopId,listingId),q);
export async function buyListing(player,shopId,listingId,quantity=1){const shop=Shops.getShop(shopId),listing=Shops.getListing(shopId,listingId),q=quote("buy",player,shop,listing,quantity);if(!q.ok)return q;if(shop.enabled===false||shop.settings?.allowBuy===false)return {ok:false,reason:"shop_buy_disabled"};if(listing.stock?.mode!=="unlimited"&&(listing.stock?.quantity??0)<q.quantity)return {ok:false,reason:"out_of_stock"};if(Economy.getBalance(player)<q.total)return {...q,ok:false,reason:"insufficient_funds"};const product=listingProduct(listing,"buy"),totalItems=product.amount*q.quantity;if(!Economy.withdraw(player,q.total,{type:"shop_purchase",source:"shop_v3",shopId,listingId,itemId:listing.typeId,itemAmount:totalItems,productId:listing.productId,fees:q.fees}))return {ok:false,reason:"charge_failed"};let delivered=true,deliveryReason="inventory_full_or_give_failed";if(listing.productId){const def=Products.get(listing.productId);if(!def){delivered=false;deliveryReason="unknown_product";}else{for(let i=0;i<q.quantity;i++){const dr=await Products.deliver(player,def,{source:"shop_v3",shopId,listingId});if(!dr?.ok){delivered=false;deliveryReason=dr?.reason??"product_delivery_failed";break;}}}}else delivered=await Inventory.give(player,product.id,totalItems,product.data);if(!delivered){Economy.deposit(player,q.total,{type:"shop_refund",source:"shop_v3",shopId,listingId,itemId:listing.typeId,itemAmount:totalItems,productId:listing.productId});return {ok:false,reason:deliveryReason};}if(listing.stock?.mode!=="unlimited")Shops.adjustStock(shopId,listingId,-q.quantity);if(shop.merchantAccount)try{Accounts.deposit(shop.merchantAccount,q.subtotal,{source:"shop_v3",shopId});}catch{}for(const f of q.fees)if(f.recipient)try{Accounts.deposit(f.recipient,f.amount,{source:"shop_fee",shopId});}catch{}return {ok:true,...q,amount:totalItems,typeId:listing.typeId};}
export async function sellListing(player,shopId,listingId,quantity=1){const shop=Shops.getShop(shopId),listing=Shops.getListing(shopId,listingId),q=quote("sell",player,shop,listing,quantity);if(!q.ok)return q;if(shop.enabled===false||shop.settings?.allowSell===false)return {ok:false,reason:"shop_sell_disabled"};const product=listingProduct(listing,"sell"),totalItems=product.amount*q.quantity;if(!await Inventory.remove(player,product.id,totalItems,product.data))return {ok:false,reason:"missing_items"};if(!Economy.deposit(player,q.total,{type:"shop_sale",source:"shop_v3",shopId,listingId,itemId:listing.typeId,itemAmount:totalItems,fees:q.fees})){await Inventory.give(player,product.id,totalItems,product.data);return {ok:false,reason:"payout_failed"};}if(listing.stock?.mode!=="unlimited")Shops.adjustStock(shopId,listingId,q.quantity);return {ok:true,...q,amount:totalItems,typeId:listing.typeId};}
// Compatibility API for legacy callers.
export async function buy(player,product,context={}){const price=Math.round(Number(product.price??product.buyPrice??0)),amount=Math.max(1,Math.round(Number(product.amount??1))),typeId=product.typeId??product.id;if(!typeId||price<0)return {ok:false,reason:"invalid_product"};if(Economy.getBalance(player)<price)return {ok:false,reason:"insufficient_funds"};if(!Economy.withdraw(player,price,{type:"shop_purchase",source:context.source??"shop",shopId:context.shopId,itemId:typeId,itemAmount:amount}))return {ok:false,reason:"charge_failed"};if(!await Inventory.give(player,typeId,amount,product.data??product.buyDamage??0)){Economy.deposit(player,price,{type:"shop_refund",source:context.source??"shop",shopId:context.shopId,itemId:typeId,itemAmount:amount});return {ok:false,reason:"inventory_full_or_give_failed"};}return {ok:true,price,amount,typeId};}
export async function sell(player,product,context={}){const price=Math.round(Number(product.price??product.sellPrice??0)),amount=Math.max(1,Math.round(Number(product.amount??1))),typeId=product.typeId??product.id;if(!typeId||price<0)return {ok:false,reason:"invalid_product"};if(!await Inventory.remove(player,typeId,amount,product.data??product.sellDamage??0))return {ok:false,reason:"missing_items"};if(!Economy.deposit(player,price,{type:"shop_sale",source:context.source??"shop",shopId:context.shopId,itemId:typeId,itemAmount:amount})){await Inventory.give(player,typeId,amount,product.data??product.sellDamage??0);return {ok:false,reason:"payout_failed"};}return {ok:true,price,amount,typeId};}
