import { world, ItemTypes } from "@minecraft/server";
import { SHOP_V3_DEFAULTS } from "../data/shop_v3_defaults.js";
import { log, LOG_LEVELS } from "../logger.js";
import { emit } from "../core/events.js";
import { shops as shopExtensions } from "../api/extensions.js";

export const SHOP_DATA_PREFIX="moneyz:shop:v3:";
export const LEGACY_SHOP_DATA_PREFIX="shop_";
export const SHOP_SCHEMA_VERSION=3;
let cache;
const clone=x=>JSON.parse(JSON.stringify(x));
const slug=s=>String(s??"").trim().toLowerCase().replace(/[^a-z0-9_:\-]+/g,"_").replace(/^_+|_+$/g,"");
const display=s=>String(s??"").replace(/^minecraft:/,"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const normalizeType=id=>{id=String(id??"").trim();return id&&!id.includes(":")?`minecraft:${id}`:id;};
export function itemExists(id){try{return !!ItemTypes.get(normalizeType(id));}catch{return false;}}
export function itemCatalog(query="",limit=150){const q=String(query).trim().toLowerCase();let all=[];try{all=ItemTypes.getAll().map(x=>x.id).sort();}catch{}if(q)all=all.filter(id=>id.toLowerCase().includes(q)||display(id).toLowerCase().includes(q));return all.slice(0,Math.max(1,limit));}
function listingFromLegacy(x,category="general",index=0){const typeId=normalizeType(x.typeId??x.id);return {id:x.listingId??`${slug(category)}:${slug(typeId)}:${index}`,typeId,name:x.name??display(typeId),category,enabled:x.enabled!==false,buy:{enabled:Number(x.buyPrice??x.buyCost)>=0,amount:Math.max(1,Number(x.buyAmount??x.amount??1)|0),price:Math.max(0,Number(x.buyPrice??x.buyCost??0)|0)},sell:{enabled:Number(x.sellPrice??x.sellCost)>=0,amount:Math.max(1,Number(x.sellAmount??x.amount??1)|0),price:Math.max(0,Number(x.sellPrice??x.sellCost??0)|0)},stock:{mode:x.stock?.mode??"unlimited",quantity:Math.max(0,Number(x.stock?.quantity??0)|0)},iconPath:x.iconPath,legacy:{buyDamage:Number(x.buyDamage??x.buyData??0)|0,sellDamage:Number(x.sellDamage??x.sellData??0)|0}};}
export function normalizeShop(id,value={}){if(value?.schemaVersion===3&&Array.isArray(value.listings))return {...value,id:value.id??id,schemaVersion:3,name:value.name??display(id),enabled:value.enabled!==false,settings:{allowBuy:true,allowSell:true,showInBrowser:true,allowDirectAccess:true,allowNpcBinding:true,permission:null,...value.settings}};const listings=[];for(const [cat,rows] of Object.entries(value??{}))if(Array.isArray(rows))rows.forEach((x,i)=>listings.push(listingFromLegacy(x,cat,i)));return {schemaVersion:3,id,name:display(id),enabled:true,merchantAccount:null,settings:{allowBuy:true,allowSell:true,stockMode:"unlimited",showInBrowser:true,allowDirectAccess:true,allowNpcBinding:true,permission:null},listings};}
function defaults(){const out={};for(const [id,data] of Object.entries(SHOP_V3_DEFAULTS))out[id]=normalizeShop(id,data);return out;}
export function reloadShops(){const next=defaults();try{for(const prop of world.getDynamicPropertyIds()){if(prop.startsWith(SHOP_DATA_PREFIX)){const id=prop.slice(SHOP_DATA_PREFIX.length),raw=world.getDynamicProperty(prop);if(typeof raw==="string")try{const parsed=JSON.parse(raw);if(parsed?.__deleted){delete next[id];continue;}next[id]=normalizeShop(id,parsed);}catch(e){log(`Shop v3 invalid ${id}: ${e}`,LOG_LEVELS.ERROR);}}else if(prop.startsWith(LEGACY_SHOP_DATA_PREFIX)){const id=prop.slice(LEGACY_SHOP_DATA_PREFIX.length);if(next[id]&&world.getDynamicProperty(SHOP_DATA_PREFIX+id)!==undefined)continue;const raw=world.getDynamicProperty(prop);if(typeof raw==="string")try{next[id]=normalizeShop(id,JSON.parse(raw));}catch{}}}}catch(e){log(`ShopRepository.reload failed: ${e}`,LOG_LEVELS.ERROR);}cache=next;emit("shopsReloaded",{count:Object.keys(next).length,schemaVersion:3});return cache;}
export const getShopData=()=>cache??reloadShops();
export const getShop=id=>getShopData()[id];
export function saveShop(id,value){id=slug(id);if(!id)throw new Error("Invalid shop id");const shop=normalizeShop(id,value);world.setDynamicProperty(SHOP_DATA_PREFIX+id,JSON.stringify(shop));cache=null;emit("shopChanged",{id,action:"save",shop});return getShop(id);}
export function createShop(def){const id=slug(def?.id);if(!id)throw new Error("Invalid shop id");if(getShop(id))throw new Error("Shop already exists");return saveShop(id,{schemaVersion:3,id,name:def.name??display(id),enabled:def.enabled!==false,merchantAccount:def.merchantAccount??null,settings:{allowBuy:true,allowSell:true,stockMode:"unlimited",showInBrowser:true,allowDirectAccess:true,allowNpcBinding:true,permission:null,...(def.settings??{})},listings:[]});}
export function updateShop(id,patch){const s=getShop(id);if(!s)throw new Error("Shop not found");return saveShop(id,{...s,...patch,settings:{...s.settings,...(patch.settings??{})}});}
export function deleteShop(id){world.setDynamicProperty(SHOP_DATA_PREFIX+id,JSON.stringify({__deleted:true,id}));world.setDynamicProperty(LEGACY_SHOP_DATA_PREFIX+id,undefined);cache=null;reloadShops();emit("shopChanged",{id,action:"delete"});}
export function listListings(shopId,{category,enabledOnly=false}={}){let a=getShop(shopId)?.listings??[];if(category)a=a.filter(x=>x.category===category);if(enabledOnly)a=a.filter(x=>x.enabled!==false);return a;}
export function getListing(shopId,listingId){return listListings(shopId).find(x=>x.id===listingId);}
export function addListing(shopId,def){const s=clone(getShop(shopId));if(!s)throw new Error("Shop not found");const typeId=normalizeType(def.typeId??def.id);if(!itemExists(typeId))throw new Error(`Unknown item type: ${typeId}`);const category=slug(def.category??"general")||"general";const listing=listingFromLegacy({...def,id:typeId,name:def.name??display(typeId),buyPrice:def.buy?.price??def.buyPrice??-1,sellPrice:def.sell?.price??def.sellPrice??-1,buyAmount:def.buy?.amount??def.amount??1,sellAmount:def.sell?.amount??def.amount??1,stock:def.stock},category,s.listings.length);listing.id=def.listingId??`${category}:${slug(typeId)}:${Date.now().toString(36)}`;s.listings.push(listing);saveShop(shopId,s);return listing;}
export function updateListing(shopId,listingId,patch){const s=clone(getShop(shopId));if(!s)throw new Error("Shop not found");const i=s.listings.findIndex(x=>x.id===listingId);if(i<0)throw new Error("Listing not found");const merged={...s.listings[i],...patch,buy:{...s.listings[i].buy,...patch.buy},sell:{...s.listings[i].sell,...patch.sell},stock:{...s.listings[i].stock,...patch.stock}};if(patch.typeId&&!itemExists(patch.typeId))throw new Error("Unknown item type");s.listings[i]=merged;saveShop(shopId,s);return merged;}
export function removeListing(shopId,listingId){const s=clone(getShop(shopId));if(!s)return false;const n=s.listings.length;s.listings=s.listings.filter(x=>x.id!==listingId);if(s.listings.length===n)return false;saveShop(shopId,s);return true;}
export function adjustStock(shopId,listingId,delta){const s=clone(getShop(shopId));const x=s?.listings.find(v=>v.id===listingId);if(!x||x.stock?.mode==="unlimited")return true;x.stock.quantity=Math.max(0,(x.stock.quantity|0)+(delta|0));saveShop(shopId,s);return true;}
export function categories(shopId){return [...new Set(listListings(shopId).map(x=>x.category??"general"))].sort();}
export function stats(){const data=getShopData();return {shops:Object.keys(data).length,categories:Object.values(data).reduce((n,s)=>n+new Set(s.listings.map(x=>x.category)).size,0),items:Object.values(data).reduce((n,s)=>n+s.listings.length,0),schemaVersion:3};}
export function list(){const builtIn=Object.values(getShopData()).map(data=>({id:data.id,source:"moneyz",data}));const external=[];for(const provider of shopExtensions.providers()){try{for(const shop of provider.getShops?.()??[])external.push({...shop,source:provider.id,provider});}catch{}}return [...builtIn,...external];}
export function providerFor(id){return shopExtensions.providers().find(p=>p.getShop?.(id)||p.getShops?.().some?.(s=>s.id===id))??null;}
export function exportShop(id){const s=getShop(id);return s?JSON.stringify(s):null;}
export function importShop(raw,{overwrite=false}={}){const obj=typeof raw==="string"?JSON.parse(raw):raw;if(!obj?.id)throw new Error("Shop import requires id");if(getShop(obj.id)&&!overwrite)throw new Error("Shop exists");return saveShop(obj.id,obj);}

export function migrateLegacyCustomShop(items,name="Custom Shop"){if(!Array.isArray(items)||!items.length)return false;const id="custom_shop";if(getShop(id)?.listings?.length)return false;const shop={schemaVersion:3,id,name,enabled:true,settings:{allowBuy:true,allowSell:true},listings:items.map((x,i)=>listingFromLegacy({id:x.id,name:x.name,buyAmount:x.buyAmount,buyCost:x.buyCost,buyData:x.buyData,sellAmount:x.sellAmount,sellCost:x.sellCost,sellData:x.sellData},"general",i))};saveShop(id,shop);return true;}
