import { system, Player, CommandPermissionLevel, CustomCommandParamType, CustomCommandStatus } from "@minecraft/server";
import * as Economy from "../core/economy.js";
import * as Transactions from "../core/transactions.js";
import { reloadShops } from "../repositories/shops.js";
import { formatHealth } from "../core/health.js";
import { runMigrations } from "../core/migrations.js";
import { main } from "../gui/moneyz_menu.js";
import * as NpcMenus from "./npc_menus.js";
import { Moneyz } from "../core/api.js";
const playerFrom=o=>o.sourceEntity instanceof Player?o.sourceEntity:undefined;
const result=(ok,message)=>({status:ok?CustomCommandStatus.Success:CustomCommandStatus.Failure,message});
export function registerCommands(registry){
 registry.registerCommand({name:"moneyz:menu",description:"Open the Moneyz menu",permissionLevel:CommandPermissionLevel.Any,cheatsRequired:false},origin=>{const p=playerFrom(origin);if(!p)return result(false,"Player only.");system.run(()=>main(p));return result(true,"Opening Moneyz.");});
 registry.registerCommand({name:"moneyz:balance",description:"Show a Moneyz balance",permissionLevel:CommandPermissionLevel.Any,cheatsRequired:false,optionalParameters:[{type:CustomCommandParamType.PlayerSelector,name:"player"}]},(origin,targets)=>{const target=targets?.[0]??playerFrom(origin);if(!target)return result(false,"No player.");return result(true,`${target.nameTag}: ${Economy.getBalance(target)} Moneyz`);});
 for(const [name,op] of [["give","deposit"],["take","withdraw"],["set","setBalance"]])registry.registerCommand({name:`moneyz:${name}`,description:`${name} Moneyz`,permissionLevel:CommandPermissionLevel.Admin,mandatoryParameters:[{type:CustomCommandParamType.PlayerSelector,name:"player"},{type:CustomCommandParamType.Integer,name:"amount"}]},(origin,targets,amount)=>{const target=targets?.[0];if(!target)return result(false,"No player.");const actor=playerFrom(origin)??"console";system.run(()=>Economy[op](target,amount,{type:"admin_adjustment",source:"custom_command",actor}));return result(true,"Moneyz update queued.");});
 registry.registerCommand({name:"moneyz:reload",description:"Reload Moneyz shop data",permissionLevel:CommandPermissionLevel.Admin},()=>{system.run(()=>reloadShops());return result(true,"Moneyz reload queued.");});
 registry.registerCommand({name:"moneyz:health",description:"Show Moneyz diagnostics",permissionLevel:CommandPermissionLevel.Admin},()=>result(true,formatHealth()));
 registry.registerCommand({name:"moneyz:migrate",description:"Run Moneyz schema migrations",permissionLevel:CommandPermissionLevel.Admin},()=>{system.run(()=>runMigrations());return result(true,"Moneyz migration queued.");});
 registry.registerCommand({name:"moneyz:transactions",description:"Show recent Moneyz transactions",permissionLevel:CommandPermissionLevel.Admin,optionalParameters:[{type:CustomCommandParamType.Integer,name:"count"}]},(_origin,count)=>{const n=Math.min(10,Math.max(1,Number(count??5)));const text=Transactions.recent(n).map(t=>`${t.id} ${t.type} ${t.amount} ${t.from??""}${t.to?` -> ${t.to}`:""}`).join(" | ")||"No transactions.";return result(true,text);});
 registry.registerCommand({name:"moneyz:npc",description:"Assign a Moneyz custom menu to an NPC. Uses nearest NPC if selector is omitted.",permissionLevel:CommandPermissionLevel.GameDirectors,mandatoryParameters:[{type:CustomCommandParamType.String,name:"menu"}],optionalParameters:[{type:CustomCommandParamType.EntitySelector,name:"npc"}]},(origin,menu,entities)=>{const player=playerFrom(origin),selected=entities?.[0];if(!player&&!selected)return result(false,"Run as a player or provide an NPC selector.");system.run(()=>{const r=selected?NpcMenus.assign(selected,menu):NpcMenus.assignNearest(player,menu);if(player)player.sendMessage(r.ok?`§aNPC assigned to ${r.menu}.`:`§cNPC setup failed: ${r.reason}. Use /moneyz:menus to list menu IDs.`);});return result(true,"NPC menu assignment queued.");});
 registry.registerCommand({name:"moneyz:menus",description:"List registered Moneyz NPC menu IDs",permissionLevel:CommandPermissionLevel.GameDirectors},()=>result(true,NpcMenus.listMenus().map(x=>x.id).join(", ")||"No menus registered."));
 registry.registerCommand({name:"moneyz:npc_clear",description:"Clear the nearest NPC's assigned Moneyz menu",permissionLevel:CommandPermissionLevel.GameDirectors},origin=>{const player=playerFrom(origin);if(!player)return result(false,"Player only.");system.run(()=>{const npc=NpcMenus.nearest(player);player.sendMessage(npc&&NpcMenus.clear(npc)?"§aMoneyz NPC menu cleared.":"§cNo NPC found within 6 blocks.");});return result(true,"NPC clear queued.");});
 registry.registerCommand({name:"moneyz:api",description:"Show Moneyz public API version and capabilities",permissionLevel:CommandPermissionLevel.GameDirectors,cheatsRequired:false},()=>result(true,`Moneyz API ${Moneyz.apiVersion}: ${Object.entries(Moneyz.capabilities).filter(([,v])=>v).map(([k])=>k).join(", ")}`));
 registry.registerCommand({name:"moneyz:extensions",description:"List registered Moneyz extensions",permissionLevel:CommandPermissionLevel.GameDirectors,cheatsRequired:false},()=>result(true,Moneyz.extensions.list().map(x=>`${x.id}@${x.version}`).join(", ")||"No third-party extensions registered."));
 registry.registerCommand({name:"moneyz:validate",description:"Validate the Moneyz runtime",permissionLevel:CommandPermissionLevel.Admin},()=>{const v=Moneyz.dev.validate(Moneyz);return result(v.ok,v.ok?`Moneyz API ${v.apiVersion} validated successfully.`:`Moneyz validation: ${v.issues.join("; ")}`);});

}
